In [1]:
import numpy as np
import tensorflow as tf
import pandas as pd
from tensorflow import *

In [2]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer1 = Tokenizer()

In [3]:
tokenizer2=Tokenizer()

In [4]:
df = pd.read_csv(r'/content/Dataset_English_Hindi.csv', encoding='utf-8-sig')

In [5]:
df

,English,Hindi
0,Help!,बचाओ!
1,Jump.,उछलो.
2,Jump.,कूदो.
3,Jump.,छलांग.
4,Hello!,नमस्ते।
...,...,...
14988,understand:the 3rd right in kuraan is for all ...,‎समझना: क़ुरआन का तीसरा हक़ हर मुसलमान पर है उ...
14989,so they painted it like this.,इसलिए उन्होंने इसे ऐसा रंग दिया है।
14990,"Otherwise , Ramalinga wrote , he himself would...",रामलिंग ने लिखा कि नरूथा वह सव्Mय भी इस तरह का...
14991,A long term Financial Agreement has helped in ...,एक दीर्घकालीन आर्थिक समझौते ने भारत के साथ अच्...
14992,BASAVA ' S REVOLUTIONARY THO,NaN

In [6]:
x=df.iloc[::,0:1]
y=df.iloc[::,1:]

In [7]:
x

                                                 English
0                                                  Help!
1                                                  Jump.
2                                                  Jump.
3                                                  Jump.
4                                                 Hello!
...                                                  ...
14988  understand:the 3rd right in kuraan is for all ...
14989                      so they painted it like this.
14990  Otherwise , Ramalinga wrote , he himself would...
14991  A long term Financial Agreement has helped in ...
14992                       BASAVA ' S REVOLUTIONARY THO

[14993 rows x 1 columns]

In [8]:
y

                                                   Hindi
0                                                  बचाओ!
1                                                  उछलो.
2                                                  कूदो.
3                                                 छलांग.
4                                                नमस्ते।
...                                                  ...
14988  ‎समझना: क़ुरआन का तीसरा हक़ हर मुसलमान पर है उ...
14989                इसलिए उन्होंने इसे ऐसा रंग दिया है।
14990  रामलिंग ने लिखा कि नरूथा वह सव्Mय भी इस तरह का...
14991  एक दीर्घकालीन आर्थिक समझौते ने भारत के साथ अच्...
14992                                                NaN

[14993 rows x 1 columns]

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=0)

In [11]:
y_train = "<START> " + y_train + " <END>"

In [12]:
x_train

                                                 English
3872   For oblation, hoarse was necessary which was s...
8                                                Got it?
1832                  He is able to speak ten languages.
13763   It was built of hard black stone in the ninth...
10664  And we want everybody else to gaze out of the ...
...                                                  ...
13123  His successor , Kalraj Mishra , insists the “ ...
3264   many opinions present regarding reasons of ter...
9845   have been done with the help of motion capture...
10799  Asia's oldest newspaper, Bombay News, is also ...
2732   She gave me a large room while I stayed at her...

[11244 rows x 1 columns]

In [13]:
x_train=np.array(x_train)

In [14]:
x_train

array([['For oblation, hoarse was necessary which was stolen by jealous Indra.'],
       ['Got it?'],
       ['He is able to speak ten languages.'],
       ...,
       ['have been done with the help of motion capture systems.'],
       ["Asia's oldest newspaper, Bombay News, is also in Mumbai."],
       ['She gave me a large room while I stayed at her house.']],
      dtype=object)

In [15]:
x_train = x_train.reshape(-1)

In [16]:
x_train

array(['For oblation, hoarse was necessary which was stolen by jealous Indra.',
       'Got it?', 'He is able to speak ten languages.', ...,
       'have been done with the help of motion capture systems.',
       "Asia's oldest newspaper, Bombay News, is also in Mumbai.",
       'She gave me a large room while I stayed at her house.'],
      dtype=object)

In [17]:
x_train=x_train[:-1]

In [18]:
x_train

array(['For oblation, hoarse was necessary which was stolen by jealous Indra.',
       'Got it?', 'He is able to speak ten languages.', ...,
       'many opinions present regarding reasons of terrorism. they say range demographic socioeconomic for political reasons. demographic factors and crowd can include high growth rate social factors, poverty, unemployment and land term problems may include disenfranchisement, ethnic confict, religious confict, territorial conflict, resources or to use for revenge',
       'have been done with the help of motion capture systems.',
       "Asia's oldest newspaper, Bombay News, is also in Mumbai."],
      dtype=object)

In [19]:
y_train=np.array(y_train)
y_train=y_train.reshape(-1)

In [20]:
y_train

array(['<START> यज्ञ के लिये घोड़ा आवश्यक था जो ईर्ष्यालु इंद्र ने चुरा लिया था। <END>',
       '<START> समझे कि नहीं? <END>',
       '<START> वह दस भाषाएँ बोलना जानता है। <END>', ...,
       '<START> गति को कब्ज़ा करने वाले कैमरों की मदद से किये गए है| <END>',
       '<START> मुंबई में ही एशिया का सबसे पुराना समाचार-पत्र बॉम्बे समाचार भी निकलता है। <END>',
       '<START> जब मैं उसके घर पर रही, उसने मुझे रहने के लिए एक बड़ा सा कमरा दिया। <END>'],
      dtype=object)

In [21]:
y_train=y_train[:-1]

In [22]:
y_train

array(['<START> यज्ञ के लिये घोड़ा आवश्यक था जो ईर्ष्यालु इंद्र ने चुरा लिया था। <END>',
       '<START> समझे कि नहीं? <END>',
       '<START> वह दस भाषाएँ बोलना जानता है। <END>', ...,
       '<START> कई राय आतंकवाद के कारणों के विषय में मौजूद हैं.वे से रेंज जनांकिकीय (demographic) को सामाजिक (socioeconomic) राजनीतिक कारणों के लिए.जनांकिकीय कारकों और भीड़ उच्च विकास दर शामिल हो सकते हैं.सामाजिक कारकों गरीबी बेरोजगारी और भूमि कार्यकाल समस्याओं शामिल हो सकते हैं.राजनैतिक कारक शामिल हो सकते हैं दिसेंफ्रंचिसेमेंट (disenfranchisement) जातीय संघर्ष (ethnic conflict) धार्मिक संघर्ष (religious conflict) प्रादेशिक संघर्ष (territorial conflict) संसाधन या भी बदला लेने का उपयोग करने के लिए. <END>',
       '<START> गति को कब्ज़ा करने वाले कैमरों की मदद से किये गए है| <END>',
       '<START> मुंबई में ही एशिया का सबसे पुराना समाचार-पत्र बॉम्बे समाचार भी निकलता है। <END>'],
      dtype=object)

In [23]:
x_train = x_train.astype(str)

In [24]:
x_train

array(['For oblation, hoarse was necessary which was stolen by jealous Indra.',
       'Got it?', 'He is able to speak ten languages.', ...,
       'many opinions present regarding reasons of terrorism. they say range demographic socioeconomic for political reasons. demographic factors and crowd can include high growth rate social factors, poverty, unemployment and land term problems may include disenfranchisement, ethnic confict, religious confict, territorial conflict, resources or to use for revenge',
       'have been done with the help of motion capture systems.',
       "Asia's oldest newspaper, Bombay News, is also in Mumbai."],
      dtype='<U1296')

In [25]:
tokenizer1.fit_on_texts(x_train)

In [26]:
len(tokenizer1.word_index)

17771

In [27]:
tokenizer1.word_index#This is our vocabulary.

{'the': 1,
 'of': 2,
 'and': 3,
 'to': 4,
 'in': 5,
 'a': 6,
 'is': 7,
 'that': 8,
 'it': 9,
 'was': 10,
 'for': 11,
 'this': 12,
 'are': 13,
 'you': 14,
 'on': 15,
 'he': 16,
 'i': 17,
 'with': 18,
 'as': 19,
 'by': 20,
 'be': 21,
 'his': 22,
 'not': 23,
 'or': 24,
 'have': 25,
 'from': 26,
 'which': 27,
 'at': 28,
 'but': 29,
 'they': 30,
 'has': 31,
 'there': 32,
 'we': 33,
 'one': 34,
 'were': 35,
 'can': 36,
 'all': 37,
 'an': 38,
 'their': 39,
 'india': 40,
 'had': 41,
 'will': 42,
 'if': 43,
 'so': 44,
 'its': 45,
 'when': 46,
 'also': 47,
 'who': 48,
 'like': 49,
 'what': 50,
 'about': 51,
 'these': 52,
 "'s": 53,
 'other': 54,
 'do': 55,
 'some': 56,
 '”': 57,
 'time': 58,
 'them': 59,
 'been': 60,
 'my': 61,
 'more': 62,
 'people': 63,
 'your': 64,
 'rrb': 65,
 'lrb': 66,
 'no': 67,
 'her': 68,
 'after': 69,
 'him': 70,
 'she': 71,
 'up': 72,
 'out': 73,
 'only': 74,
 'made': 75,
 'me': 76,
 'two': 77,
 'years': 78,
 'many': 79,
 'very': 80,
 'than': 81,
 'may': 82,
 'any': 83,
 'our': 84,
 'into': 85,
 'world': 86,
 'indian': 87,
 "'": 88,
 'would': 89,
 'because': 90,
 'first': 91,
 'should': 92,
 'government': 93,
 'now': 94,
 'then': 95,
 'go': 96,
 'where': 97,
 'how': 98,
 'new': 99,
 "it's": 100,
 'did': 101,
 'called': 102,
 'get': 103,
 'even': 104,
 'over': 105,
 'take': 106,
 'life': 107,
 'work': 108,
 'before': 109,
 'us': 110,
 'well': 111,
 'most': 112,
 'state': 113,
 'make': 114,
 'being': 115,
 'here': 116,
 'year': 117,
 'during': 118,
 'see': 119,
 'those': 120,
 'three': 121,
 'under': 122,
 'could': 123,
 'know': 124,
 'day': 125,
 'such': 126,
 'way': 127,
 'used': 128,
 'man': 129,
 "don't": 130,
 'much': 131,
 '“': 132,
 'same': 133,
 'between': 134,
 'through': 135,
 'help': 136,
 'said': 137,
 'country': 138,
 'want': 139,
 'every': 140,
 'power': 141,
 'going': 142,
 'come': 143,
 'water': 144,
 'different': 145,
 'while': 146,
 'just': 147,
 'court': 148,
 'both': 149,
 'long': 150,
 'house': 151,
 'good': 152,
 'great': 153,
 'hindi': 154,
 'down': 155,
 'use': 156,
 "i'm": 157,
 'back': 158,
 'number': 159,
 'part': 160,
 'per': 161,
 'own': 162,
 'each': 163,
 'got': 164,
 'place': 165,
 'give': 166,
 'english': 167,
 'parliament': 168,
 '1': 169,
 'congress': 170,
 'city': 171,
 'old': 172,
 'last': 173,
 'british': 174,
 'given': 175,
 'must': 176,
 'name': 177,
 'important': 178,
 'million': 179,
 'does': 180,
 'think': 181,
 'human': 182,
 'war': 183,
 'home': 184,
 'days': 185,
 'four': 186,
 'say': 187,
 'god': 188,
 'religion': 189,
 'national': 190,
 'started': 191,
 'another': 192,
 'political': 193,
 'why': 194,
 'later': 195,
 'children': 196,
 'law': 197,
 'air': 198,
 'person': 199,
 'too': 200,
 'today': 201,
 'little': 202,
 'south': 203,
 'book': 204,
 'still': 205,
 'took': 206,
 'against': 207,
 'president': 208,
 'right': 209,
 'money': 210,
 'public': 211,
 'without': 212,
 '2': 213,
 'done': 214,
 'left': 215,
 'main': 216,
 'small': 217,
 'found': 218,
 'according': 219,
 'men': 220,
 'become': 221,
 'however': 222,
 'large': 223,
 'age': 224,
 'around': 225,
 'put': 226,
 'taken': 227,
 'came': 228,
 '3': 229,
 'language': 230,
 'high': 231,
 'party': 232,
 'since': 233,
 'need': 234,
 'family': 235,
 'system': 236,
 'constitution': 237,
 'went': 238,
 'form': 239,
 'off': 240,
 'end': 241,
 'few': 242,
 'period': 243,
 'always': 244,
 'love': 245,
 'position': 246,
 'hindu': 247,
 'never': 248,
 'health': 249,
 'away': 250,
 'child': 251,
 'present': 252,
 'father': 253,
 '000': 254,
 'things': 255,
 'though': 256,
 'am': 257,
 'live': 258,
 'group': 259,
 'again': 260,
 'among': 261,
 'general': 262,
 'known': 263,
 'less': 264,
 'something': 265,
 'case': 266,
 'problem': 267,
 '5': 268,
 'tell': 269,
 'lot': 270,
 'social': 271,
 'members': 272,
 'committee': 273,
 'times': 274,
 'due': 275,
 'next': 276,
 'district': 277,
 'modern': 278,
 'common': 279,
 'laughter': 280,
 'really': 281,
 'special': 282,
 'school': 283,
 'fact': 284,
 'side': 285,
 'second': 286,
 'religious': 287,
 'hand': 288,
 'class': 289,
 'believe': 290,
 'food': 291,
 'mumbai': 292,
 'body': 293,
 'service': 294,
 '4': 295,
 'countries': 296,
 'states': 297,
 'culture': 298,
 'written': 299,
 'king': 300,
 'mind': 301,
 'able': 302,
 'best': 303,
 'once': 304,
 'big': 305,
 'became': 306,
 'cannot': 307,
 'five': 308,
 'yet': 309,
 'e': 310,
 'parts': 311,
 'women': 312,
 'area': 313,
 'minister': 314,
 'along': 315,
 'death': 316,
 'doing': 317,
 'might': 318,
 'says': 319,
 'mobile': 320,
 'cent': 321,
 'upon': 322,
 'mother': 323,
 'whole': 324,
 'early': 325,
 "that's": 326,
 'nothing': 327,
 'history': 328,
 'river': 329,
 'working': 330,
 'please': 331,
 'keep': 332,
 'changes': 333,
 'story': 334,
 'look': 335,
 'cricket': 336,
 'temple': 337,
 'books': 338,
 'others': 339,
 'find': 340,
 'within': 341,
 'various': 342,
 'control': 343,
 'century': 344,
 'local': 345,
 'etc': 346,
 'education': 347,
 'based': 348,
 'muslims': 349,
 'talk': 350,
 '10': 351,
 'result': 352,
 'better': 353,
 'pakistan': 354,
 'third': 355,
 'brought': 356,
 'act': 357,
 'course': 358,
 'sabha': 359,
 'information': 360,
 'therefore': 361,
 'behind': 362,
 'sanskrit': 363,
 'development': 364,
 'actually': 365,
 'phone': 366,
 'earth': 367,
 'possible': 368,
 'land': 369,
 'famous': 370,
 'half': 371,
 'set': 372,
 'muslim': 373,
 'call': 374,
 'view': 375,
 'industry': 376,
 'delhi': 377,
 'woman': 378,
 'hard': 379,
 'thing': 380,
 'having': 381,
 'matter': 382,
 'already': 383,
 'either': 384,
 'free': 385,
 'making': 386,
 "n't": 387,
 'category': 388,
 'thus': 389,
 'point': 390,
 'change': 391,
 'far': 392,
 'ganga': 393,
 'non': 394,
 'true': 395,
 'music': 396,
 'six': 397,
 'chief': 398,
 'simple': 399,
 "can't": 400,
 'himself': 401,
 'article': 402,
 'north': 403,
 'runs': 404,
 'play': 405,
 'young': 406,
 'support': 407,
 'comes': 408,
 'near': 409,
 'head': 410,
 'available': 411,
 'getting': 412,
 'enough': 413,
 'ball': 414,
 'together': 415,
 'temples': 416,
 'son': 417,
 'earlier': 418,
 'month': 419,
 'question': 420,
 'means': 421,
 'show': 422,
 'order': 423,
 'office': 424,
 'till': 425,
 'front': 426,
 'akbar': 427,
 'cave': 428,
 'face': 429,
 'turn': 430,
 'including': 431,
 'police': 432,
 'bill': 433,
 'run': 434,
 'full': 435,
 'words': 436,
 'prime': 437,
 'video': 438,
 'further': 439,
 'terrorism': 440,
 'england': 441,
 'future': 442,
 'thought': 443,
 'team': 444,
 'krishna': 445,
 'almost': 446,
 'months': 447,
 'foreign': 448,
 'business': 449,
 'living': 450,
 'capital': 451,
 'hands': 452,
 'assembly': 453,
 'try': 454,
 'languages': 455,
 'leave': 456,
 'community': 457,
 'plan': 458,
 'international': 459,
 'economic': 460,
 'policy': 461,
 'middle': 462,
 'east': 463,
 'region': 464,
 "we're": 465,
 'courts': 466,
 'increased': 467,
 'open': 468,
 'process': 469,
 'poor': 470,
 'wrote': 471,
 'central': 472,
 'certain': 473,
 'union': 474,
 'feel': 475,
 'movement': 476,
 'problems': 477,
 'west': 478,
 'light': 479,
 'march': 480,
 'population': 481,
 'houses': 482,
 "didn't": 483,
 'often': 484,
 'c': 485,
 'itself': 486,
 'real': 487,
 'production': 488,
 'kind': 489,
 'america': 490,
 'role': 491,
 'terms': 492,
 'cases': 493,
 'self': 494,
 'festival': 495,
 'subject': 496,
 'level': 497,
 'usually': 498,
 'ram': 499,
 'told': 500,
 'village': 501,
 'groups': 502,
 'heart': 503,
 'inside': 504,
 'above': 505,
 'speak': 506,
 '20': 507,
 '6': 508,
 'beginning': 509,
 'china': 510,
 '7': 511,
 'justice': 512,
 'gave': 513,
 'ago': 514,
 'seen': 515,
 'idea': 516,
 'nepal': 517,
 'asked': 518,
 'rather': 519,
 'several': 520,
 'happened': 521,
 'word': 522,
 'let': 523,
 'literature': 524,
 'council': 525,
 'member': 526,
 'lord': 527,
 'field': 528,
 'room': 529,
 'singh': 530,
 'coming': 531,
 'short': 532,
 'applause': 533,
 'effect': 534,
 'film': 535,
 'questions': 536,
 'using': 537,
 'united': 538,
 's': 539,
 'past': 540,
 'job': 541,
 'died': 542,
 'outside': 543,
 'born': 544,
 'freedom': 545,
 'sea': 546,
 "i'll": 547,
 'quality': 548,
 'industries': 549,
 'passed': 550,
 'following': 551,
 'roy': 552,
 'line': 553,
 'individual': 554,
 'developed': 555,
 'ever': 556,
 'batsman': 557,
 'demand': 558,
 'reason': 559,
 'example': 560,
 'company': 561,
 'ten': 562,
 'built': 563,
 'top': 564,
 'gandhi': 565,
 'soon': 566,
 'structure': 567,
 'total': 568,
 'independence': 569,
 'capacity': 570,
 'named': 571,
 'doctor': 572,
 'type': 573,
 'interest': 574,
 'least': 575,
 'single': 576,
 'meet': 577,
 'art': 578,
 'decided': 579,
 'research': 580,
 'published': 581,
 'match': 582,
 'considered': 583,
 'bring': 584,
 'whether': 585,
 'industrial': 586,
 'taking': 587,
 'perhaps': 588,
 'pollution': 589,
 'truth': 590,
 'nature': 591,
 'brother': 592,
 'islam': 593,
 'entire': 594,
 'services': 595,
 'personal': 596,
 'car': 597,
 'bengal': 598,
 'base': 599,
 '14': 600,
 'played': 601,
 'start': 602,
 'care': 603,
 'understand': 604,
 'technology': 605,
 'reading': 606,
 'hindus': 607,
 'society': 608,
 'clear': 609,
 'wrong': 610,
 'towards': 611,
 'experience': 612,
 'heard': 613,
 'similar': 614,
 'election': 615,
 'held': 616,
 'places': 617,
 'rule': 618,
 'established': 619,
 'voice': 620,
 'natural': 621,
 'wall': 622,
 'increase': 623,
 'difficult': 624,
 'supreme': 625,
 'knowledge': 626,
 'ask': 627,
 'tom': 628,
 'friends': 629,
 'news': 630,
 'wanted': 631,
 'growth': 632,
 'needs': 633,
 'themselves': 634,
 'species': 635,
 'rate': 636,
 'seven': 637,
 'highest': 638,
 'tomorrow': 639,
 'army': 640,
 'nearly': 641,
 'garden': 642,
 'videos': 643,
 'blood': 644,
 'bad': 645,
 'b': 646,
 'stop': 647,
 'rs': 648,
 'major': 649,
 'january': 650,
 'building': 651,
 'happy': 652,
 'saw': 653,
 'ancient': 654,
 'majority': 655,
 'areas': 656,
 'wife': 657,
 'size': 658,
 'post': 659,
 'goods': 660,
 'pradesh': 661,
 'spread': 662,
 'powers': 663,
 'cell': 664,
 "there's": 665,
 "you're": 666,
 'door': 667,
 'longer': 668,
 'except': 669,
 'europe': 670,
 'series': 671,
 'becomes': 672,
 'style': 673,
 'writing': 674,
 'bombay': 675,
 'philosophy': 676,
 'instead': 677,
 'situation': 678,
 'm': 679,
 'lives': 680,
 '9': 681,
 '15': 682,
 'read': 683,
 'close': 684,
 'space': 685,
 'poet': 686,
 'eight': 687,
 'until': 688,
 'issue': 689,
 'sent': 690,
 'finally': 691,
 'yesterday': 692,
 'saying': 693,
 '50': 694,
 'speaker': 695,
 'letter': 696,
 'feed': 697,
 'fine': 698,
 'cut': 699,
 '11': 700,
 'official': 701,
 'difference': 702,
 'matters': 703,
 'beautiful': 704,
 "they're": 705,
 'responsible': 706,
 'cost': 707,
 'solar': 708,
 'teacher': 709,
 'provide': 710,
 'everyone': 711,
 'ministers': 712,
 'popular': 713,
 'legs': 714,
 'answer': 715,
 'transport': 716,
 'night': 717,
 'rich': 718,
 'action': 719,
 'indians': 720,
 'ground': 721,
 'lok': 722,
 'works': 723,
 'cells': 724,
 'science': 725,
 'western': 726,
 'rights': 727,
 'poems': 728,
 'necessary': 729,
 'cause': 730,
 'study': 731,
 'square': 732,
 '25': 733,
 'spirit': 734,
 'rules': 735,
 'plants': 736,
 'player': 737,
 'activities': 738,
 'fast': 739,
 'energy': 740,
 'ideas': 741,
 'anything': 742,
 'allowed': 743,
 'forms': 744,
 'meaning': 745,
 'makes': 746,
 'mean': 747,
 "what's": 748,
 'types': 749,
 'began': 750,
 'generation': 751,
 'met': 752,
 "i've": 753,
 'japan': 754,
 'fire': 755,
 'judge': 756,
 'joint': 757,
 'described': 758,
 'forward': 759,
 'kashmir': 760,
 'internet': 761,
 'media': 762,
 'friend': 763,
 'laws': 764,
 'lost': 765,
 'road': 766,
 'islands': 767,
 'tv': 768,
 'animals': 769,
 'related': 770,
 'stand': 771,
 'contact': 772,
 'conference': 773,
 'quite': 774,
 'basic': 775,
 '12': 776,
 'cities': 777,
 'tried': 778,
 'move': 779,
 'shall': 780,
 'percent': 781,
 'students': 782,
 'commission': 783,
 'produced': 784,
 'ways': 785,
 'worked': 786,
 'whose': 787,
 "let's": 788,
 'attack': 789,
 'vajpayee': 790,
 'evidence': 791,
 'stone': 792,
 'university': 793,
 'p': 794,
 'generally': 795,
 'legislative': 796,
 'importance': 797,
 'red': 798,
 'd': 799,
 'kept': 800,
 'opportunity': 801,
 '40': 802,
 'nehru': 803,
 'ill': 804,
 'train': 805,
 'beyond': 806,
 'return': 807,
 'wish': 808,
 'complete': 809,
 'conditions': 810,
 'low': 811,
 'respect': 812,
 'male': 813,
 'progress': 814,
 'provided': 815,
 'coal': 816,
 'list': 817,
 'particularly': 818,
 'sun': 819,
 'hours': 820,
 'governor': 821,
 'looking': 822,
 'civil': 823,
 'kids': 824,
 'speed': 825,
 'continue': 826,
 'executive': 827,
 'sex': 828,
 'black': 829,
 'check': 830,
 'computer': 831,
 'april': 832,
 'stage': 833,
 'feeling': 834,
 'divided': 835,
 'plant': 836,
 'tonnes': 837,
 'looked': 838,
 'higher': 839,
 'follow': 840,
 'income': 841,
 'write': 842,
 'continued': 843,
 'pay': 844,
 'account': 845,
 'names': 846,
 'limited': 847,
 'eyes': 848,
 'create': 849,
 '0': 850,
 'cultural': 851,
 'revolution': 852,
 'nations': 853,
 'largest': 854,
 '13': 855,
 'matches': 856,
 'shows': 857,
 'rest': 858,
 'administration': 859,
 'extent': 860,
 'security': 861,
 'particular': 862,
 'board': 863,
 'democracy': 864,
 "doesn't": 865,
 'gives': 866,
 'growing': 867,
 'week': 868,
 'value': 869,
 '200': 870,
 'created': 871,
 'greater': 872,
 'test': 873,
 'purpose': 874,
 'leaders': 875,
 'officers': 876,
 'bit': 877,
 'session': 878,
 "we've": 879,
 'pass': 880,
 'dog': 881,
 'politics': 882,
 'opinion': 883,
 'external': 884,
 'mahabharata': 885,
 'won': 886,
 'vishnu': 887,
 'sense': 888,
 'seems': 889,
 'paper': 890,
 'statement': 891,
 'white': 892,
 'looks': 893,
 'increasing': 894,
 'mostly': 895,
 'sometimes': 896,
 'basis': 897,
 'centre': 898,
 'upper': 899,
 'stay': 900,
 'cold': 901,
 'remember': 902,
 'killed': 903,
 'calcutta': 904,
 'temperature': 905,
 'thank': 906,
 'mountain': 907,
 'visit': 908,
 'wants': 909,
 'directly': 910,
 'traditional': 911,
 'message': 912,
 'remains': 913,
 'force': 914,
 'throughout': 915,
 'covered': 916,
 'charge': 917,
 'november': 918,
 'talking': 919,
 'stories': 920,
 'source': 921,
 'insects': 922,
 'environment': 923,
 '30': 924,
 'takes': 925,
 'global': 926,
 'game': 927,
 'goes': 928,
 'financial': 929,
 'thinking': 930,
 'vedas': 931,
 'africa': 932,
 'round': 933,
 'section': 934,
 'agree': 935,
 'everything': 936,
 'decision': 937,
 '60': 938,
 '2006': 939,
 'strong': 940,
 'across': 941,
 'offer': 942,
 'apart': 943,
 'regions': 944,
 'peace': 945,
 'keeping': 946,
 'hope': 947,
 'daily': 948,
 'interested': 949,
 'practice': 950,
 'judges': 951,
 'recent': 952,
 'disease': 953,
 'bank': 954,
 'model': 955,
 'situated': 956,
 'easily': 957,
 'agra': 958,
 'southern': 959,
 'student': 960,
 'material': 961,
 'deep': 962,
 'morning': 963,
 'market': 964,
 'workers': 965,
 'youtube': 966,
 'complex': 967,
 'shape': 968,
 "he's": 969,
 'ones': 970,
 'oil': 971,
 'die': 972,
 'shown': 973,
 'husband': 974,
 'someone': 975,
 'rajasthan': 976,
 'average': 977,
 'rajya': 978,
 '400': 979,
 'mental': 980,
 'islamic': 981,
 'additional': 982,
 'sugar': 983,
 'report': 984,
 'decisions': 985,
 'especially': 986,
 'paid': 987,
 'changed': 988,
 'mass': 989,
 'phase': 990,
 'june': 991,
 'lower': 992,
 'website': 993,
 'american': 994,
 'standing': 995,
 'deal': 996,
 'buddha': 997,
 'gets': 998,
 'waiting': 999,
 'inner': 1000,
 ...}

In [28]:
y_train=y_train.astype(str)

In [29]:
tokenizer2.fit_on_texts(y_train)

In [30]:
tokenizer2.word_index#This is our vocabulary.

{'start': 1,
 'end': 2,
 'के': 3,
 'में': 4,
 'है': 5,
 'की': 6,
 'और': 7,
 'से': 8,
 'को': 9,
 'का': 10,
 'हैं': 11,
 'पर': 12,
 'एक': 13,
 'कि': 14,
 'भी': 15,
 'नहीं': 16,
 'यह': 17,
 'है।': 18,
 'लिए': 19,
 'इस': 20,
 'हो': 21,
 'कर': 22,
 'ने': 23,
 'जो': 24,
 'ही': 25,
 'था': 26,
 'तो': 27,
 'करने': 28,
 'वह': 29,
 'किया': 30,
 'या': 31,
 'अपने': 32,
 'मैं': 33,
 'गया': 34,
 'कुछ': 35,
 'हैं।': 36,
 'तथा': 37,
 'साथ': 38,
 'तक': 39,
 'वे': 40,
 "'": 41,
 'आप': 42,
 'भारत': 43,
 'थे': 44,
 'बहुत': 45,
 'क्या': 46,
 'रूप': 47,
 'सकता': 48,
 'कोई': 49,
 'ये': 50,
 'हम': 51,
 'जाता': 52,
 'किसी': 53,
 'ऊण्श्छ्ष्': 54,
 'बाद': 55,
 'थी': 56,
 'द्वारा': 57,
 'अपनी': 58,
 'दिया': 59,
 'करते': 60,
 'जब': 61,
 'समय': 62,
 'जा': 63,
 'होता': 64,
 'मुझे': 65,
 'रहे': 66,
 'उनके': 67,
 'तरह': 68,
 'होने': 69,
 'न': 70,
 'उसे': 71,
 'सकते': 72,
 'वाले': 73,
 'रहा': 74,
 'हुआ': 75,
 'अधिक': 76,
 'करना': 77,
 'लेकिन': 78,
 'उस': 79,
 'होती': 80,
 'पहले': 81,
 'हुए': 82,
 'उसके': 83,
 'काम': 84,
 'बात': 85,
 'कम': 86,
 'इसके': 87,
 'था।': 88,
 'दो': 89,
 'जैसे': 90,
 'कारण': 91,
 'उन्हें': 92,
 'करता': 93,
 'बारे': 94,
 'उन्होंने': 95,
 'कहा': 96,
 'पास': 97,
 'इन': 98,
 'चाहिए': 99,
 'उसने': 100,
 'हुई': 101,
 'अब': 102,
 'सभी': 103,
 'जाने': 104,
 'उनकी': 105,
 'सरकार': 106,
 'अन्य': 107,
 'लोगों': 108,
 'लोग': 109,
 '।': 110,
 'प्रकार': 111,
 'होते': 112,
 'गई': 113,
 'भारतीय': 114,
 'गए': 115,
 'रही': 116,
 'जाती': 117,
 'सबसे': 118,
 'इसे': 119,
 'बार': 120,
 'नाम': 121,
 'मेरे': 122,
 'कई': 123,
 'तुम': 124,
 'मे': 125,
 'अगर': 126,
 'यदि': 127,
 'वो': 128,
 'एवं': 129,
 'दिन': 130,
 'मैंने': 131,
 'फिर': 132,
 'उन': 133,
 'उसकी': 134,
 'ऐसा': 135,
 'होगा': 136,
 'जाते': 137,
 'आपको': 138,
 'जीवन': 139,
 'साल': 140,
 'व': 141,
 'अलग': 142,
 'वाली': 143,
 'लिये': 144,
 'केवल': 145,
 'तब': 146,
 'देश': 147,
 'ऐसे': 148,
 'अपना': 149,
 'बीच': 150,
 'क्योंकि': 151,
 'हूँ।': 152,
 'कभी': 153,
 'ओर': 154,
 'आ': 155,
 'लिया': 156,
 'हूँ': 157,
 'हमारे': 158,
 'उसका': 159,
 'दूसरे': 160,
 'सकती': 161,
 'हर': 162,
 'राज्य': 163,
 'करती': 164,
 'तीन': 165,
 'दी': 166,
 'वर्ष': 167,
 'क्षेत्र': 168,
 'प्राप्त': 169,
 'ले': 170,
 'यहाँ': 171,
 'दोनों': 172,
 'शुरू': 173,
 'मेरी': 174,
 'उनका': 175,
 'धर्म': 176,
 'विशेष': 177,
 'जाना': 178,
 'इसका': 179,
 'देने': 180,
 'बाहर': 181,
 'अनुसार': 182,
 'हमें': 183,
 'गये': 184,
 'अभी': 185,
 'घर': 186,
 'कार्य': 187,
 'गयी': 188,
 'दे': 189,
 'विचार': 190,
 'सन्': 191,
 'पता': 192,
 'पूर्व': 193,
 'लगभग': 194,
 'इससे': 195,
 'थे।': 196,
 'बना': 197,
 'लगता': 198,
 'विश्व': 199,
 'आज': 200,
 'प्रयोग': 201,
 'ज्यादा': 202,
 'भाग': 203,
 'इसलिए': 204,
 '”': 205,
 'इसी': 206,
 'दौरान': 207,
 'जिसमें': 208,
 'इसमें': 209,
 'गया।': 210,
 'बड़ी': 211,
 'सब': 212,
 'बन': 213,
 'संसद': 214,
 'प्रति': 215,
 'श्रेणी': 216,
 'कहते': 217,
 'यहां': 218,
 'दुनिया': 219,
 'उपयोग': 220,
 'काफी': 221,
 'जिसे': 222,
 'सी': 223,
 'मदद': 224,
 'विकास': 225,
 'मंदिर': 226,
 'होना': 227,
 'देते': 228,
 'उससे': 229,
 'सामान्य': 230,
 'यही': 231,
 'थी।': 232,
 'मेरा': 233,
 '1': 234,
 'प्रतिशत': 235,
 'दिया।': 236,
 'बड़े': 237,
 'पूरी': 238,
 'जहां': 239,
 'ऐसी': 240,
 'संविधान': 241,
 'लाख': 242,
 'प्रमुख': 243,
 'स्थान': 244,
 'किए': 245,
 'सहायता': 246,
 'हिन्दी': 247,
 'छोटे': 248,
 'पूरा': 249,
 'महत्वपूर्ण': 250,
 'जिस': 251,
 'शामिल': 252,
 'कांग्रेस': 253,
 'लगा': 254,
 'इसकी': 255,
 'न्यायालय': 256,
 'सामने': 257,
 'शहर': 258,
 'आगे': 259,
 'बनाने': 260,
 'किया।': 261,
 'आदि': 262,
 'अच्छा': 263,
 'बिना': 264,
 'आधार': 265,
 'पानी': 266,
 'बच्चे': 267,
 'जी': 268,
 'व्यक्ति': 269,
 'चाहते': 270,
 'करें': 271,
 'चार': 272,
 'नही': 273,
 'हमारी': 274,
 'अनेक': 275,
 'दक्षिण': 276,
 'युद्ध': 277,
 'देता': 278,
 'अथवा': 279,
 'हमने': 280,
 'उत्तर': 281,
 'वाला': 282,
 'निर्माण': 283,
 'काल': 284,
 'मिल': 285,
 'जैसा': 286,
 'जिसके': 287,
 'किये': 288,
 'पीछे': 289,
 'बड़ा': 290,
 'कैसे': 291,
 'दूसरी': 292,
 'बच्चों': 293,
 'सभा': 294,
 'अधिकार': 295,
 'जिससे': 296,
 'विभिन्न': 297,
 'किंतु': 298,
 'देखा': 299,
 'तौर': 300,
 'योजना': 301,
 'राष्ट्रीय': 302,
 'समान': 303,
 'स्थिति': 304,
 'समूह': 305,
 'परिवर्तन': 306,
 'हों': 307,
 'उद्योग': 308,
 'स्थित': 309,
 'उत्पादन': 310,
 'सदस्य': 311,
 'प्रभाव': 312,
 'देना': 313,
 'शायद': 314,
 'ऊपर': 315,
 'रहता': 316,
 'उपलब्ध': 317,
 'आतंकवाद': 318,
 'कल': 319,
 'जिसका': 320,
 'गंगा': 321,
 'आर्थिक': 322,
 'रहते': 323,
 'शिक्षा': 324,
 'भाष्': 325,
 'मगर': 326,
 'मुख्य': 327,
 'सारे': 328,
 'भाषा': 329,
 'वहाँ': 330,
 'बल्कि': 331,
 'दूर': 332,
 'तैयार': 333,
 'आने': 334,
 'लेने': 335,
 'नदी': 336,
 'प्रत्येक': 337,
 'मूल': 338,
 'रह': 339,
 'राय': 340,
 'शरीर': 341,
 'हमेशा': 342,
 'हाथ': 343,
 'आपके': 344,
 'जबकि': 345,
 'लेकर': 346,
 'ए': 347,
 'सेवा': 348,
 'मोबाइल': 349,
 'देख': 350,
 'इस्तेमाल': 351,
 'तुम्हें': 352,
 'क्रिकेट': 353,
 'मत': 354,
 'क्यों': 355,
 'सके': 356,
 'वर्षों': 357,
 'जानकारी': 358,
 'जाए': 359,
 'शब्द': 360,
 'जाये': 361,
 'करके': 362,
 'परंतु': 363,
 'ज़्यादा': 364,
 'हे': 365,
 'पोजीशन': 366,
 'मामले': 367,
 'माना': 368,
 'क्षमता': 369,
 'प्रथम': 370,
 'अकबर': 371,
 'नीचे': 372,
 'व्यवस्था': 373,
 'कोशिश': 374,
 'वापस': 375,
 'वर्ग': 376,
 'स्वीकार': 377,
 'वजह': 378,
 'स्तर': 379,
 'इनमें': 380,
 'विधि': 381,
 'पार्टी': 382,
 'ध्यान': 383,
 'आकार': 384,
 'थीं': 385,
 'समस्या': 386,
 'तुम्हारे': 387,
 'परिवार': 388,
 'लगे': 389,
 'उनमें': 390,
 'वहां': 391,
 'स्वयं': 392,
 'आदमी': 393,
 'सामाजिक': 394,
 'पैदा': 395,
 'भर': 396,
 'ठीक': 397,
 'रहने': 398,
 'प्रक्रिया': 399,
 'लग': 400,
 'हूं': 401,
 'रखा': 402,
 'अंग्रेजी': 403,
 'जगह': 404,
 'उत्पन्न': 405,
 'पिछले': 406,
 'महिला': 407,
 'उसी': 408,
 'ब्रिटिश': 409,
 'चाहता': 410,
 'पहली': 411,
 'अच्छी': 412,
 'राजा': 413,
 'करीब': 414,
 '2': 415,
 'आम': 416,
 'खाना': 417,
 'संगीत': 418,
 'अर्थ': 419,
 'अमेरिका': 420,
 'आधुनिक': 421,
 'राम': 422,
 'पूरे': 423,
 'फोन': 424,
 'इतिहास': 425,
 'वास्तव': 426,
 'सही': 427,
 'मुंबई': 428,
 'दृष्टि': 429,
 'जहाँ': 430,
 'दस': 431,
 'आता': 432,
 'कुल': 433,
 'जैसी': 434,
 'जल': 435,
 'प्रस्ताव': 436,
 'खेल': 437,
 '3': 438,
 'पाकिस्तान': 439,
 'रखने': 440,
 'मानव': 441,
 'पिता': 442,
 'प्रदान': 443,
 'बंद': 444,
 'विकसित': 445,
 'स्थापित': 446,
 'देशों': 447,
 'राष्ट्रपति': 448,
 'समिति': 449,
 'साहित्य': 450,
 'देती': 451,
 'एस': 452,
 'संस्कृत': 453,
 'सरकारी': 454,
 'स्कूल': 455,
 'मात्रा': 456,
 'मध्य': 457,
 'पसंद': 458,
 'किताब': 459,
 'निर्णय': 460,
 'बजे': 461,
 'अध्यक्ष': 462,
 'दिनों': 463,
 'अंत': 464,
 'चल': 465,
 'यात्रा': 466,
 'होकर': 467,
 'इतना': 468,
 'आया': 469,
 'दिल्ली': 470,
 'अधिकांश': 471,
 'लिखा': 472,
 'छोड़': 473,
 'धीरे': 474,
 'चीन': 475,
 'चाहे': 476,
 'वर्तमान': 477,
 'पुरुष': 478,
 'of': 479,
 'होगी': 480,
 'क्षेत्रों': 481,
 'शक्ति': 482,
 'मामलों': 483,
 'समाज': 484,
 'संबंध': 485,
 'महाभारत': 486,
 'मनुष्य': 487,
 'धार्मिक': 488,
 'मिलने': 489,
 'संघ': 490,
 'स्पष्ट': 491,
 'मांग': 492,
 'कमी': 493,
 'बनी': 494,
 'तुम्हे': 495,
 'नई': 496,
 'इन्हें': 497,
 'प्रवेश': 498,
 'स्थानीय': 499,
 'समर्थन': 500,
 'भूमिका': 501,
 'मन': 502,
 'तरीके': 503,
 'सुरक्षा': 504,
 'सिर्फ': 505,
 'बल्लेबाज': 506,
 'बस': 507,
 'जानते': 508,
 'दूसरा': 509,
 'उनसे': 510,
 'विश्वास': 511,
 'चला': 512,
 'इनके': 513,
 'बनाया': 514,
 'महीने': 515,
 'वृद्धि': 516,
 'प्रयास': 517,
 'अच्छे': 518,
 '5': 519,
 'संस्कृति': 520,
 'आंदोलन': 521,
 'टीम': 522,
 'भीतर': 523,
 'उसको': 524,
 'हेतु': 525,
 'चुके': 526,
 'अलावा': 527,
 'अंतिम': 528,
 'रंग': 529,
 'देर': 530,
 'मतलब': 531,
 'बेहतर': 532,
 'प्रश्न': 533,
 'रन': 534,
 'विदेशी': 535,
 'मृत्यु': 536,
 'आवश्यकता': 537,
 'हिन्दू': 538,
 'बाहरी': 539,
 'सीमित': 540,
 'स्वास्थ्य': 541,
 'याद': 542,
 'प्रणाली': 543,
 'कहाँ': 544,
 'जारी': 545,
 'रचना': 546,
 'प्रेम': 547,
 'आती': 548,
 'उदाहरण': 549,
 'आवश्यक': 550,
 'मुझसे': 551,
 'गुफा': 552,
 'चुका': 553,
 'खुद': 554,
 'राजनीतिक': 555,
 'स्वतंत्रता': 556,
 'मिलता': 557,
 'विषय': 558,
 'कंपनी': 559,
 'संयुक्त': 560,
 'हाल': 561,
 'नये': 562,
 'पहला': 563,
 'राजनैतिक': 564,
 'नियंत्रण': 565,
 'पैसे': 566,
 'आपकी': 567,
 'संख्या': 568,
 'पुलिस': 569,
 'दिखाई': 570,
 'बताया': 571,
 'लक्ष्य': 572,
 'अधीन': 573,
 'राज़्य': 574,
 'समाप्त': 575,
 'गेंद': 576,
 'the': 577,
 'भाई': 578,
 'इस्लाम': 579,
 'कहीं': 580,
 'लाभ': 581,
 'करेंगे': 582,
 'चाहिए।': 583,
 'पत्र': 584,
 'लेते': 585,
 'बदल': 586,
 'महत्व': 587,
 'नयी': 588,
 'सदन': 589,
 'जनता': 590,
 'मीटर': 591,
 'श्री': 592,
 'सत्ता': 593,
 'हालांकि': 594,
 'सुधार': 595,
 'नीति': 596,
 'उम्र': 597,
 'अंग्रेज़ी': 598,
 'सलाह': 599,
 'किस': 600,
 'परिणाम': 601,
 'बनाए': 602,
 'वास्तविक': 603,
 'संख़्या': 604,
 'उच्च': 605,
 'जवाब': 606,
 'चुनाव': 607,
 'छोटी': 608,
 'क़्योंकि': 609,
 'निश्चित': 610,
 'गांधी': 611,
 'वही': 612,
 'बने': 613,
 'उसमें': 614,
 'पृथ्वी': 615,
 'मानते': 616,
 'अपेक्षा': 617,
 'विज्ञान': 618,
 'कौन': 619,
 'अनुच्छेद': 620,
 'दिए': 621,
 'ताकि': 622,
 'अंदर': 623,
 'जिनके': 624,
 'सहित': 625,
 'प्रदेश': 626,
 'निर्मित': 627,
 'उचित': 628,
 'वायु': 629,
 'पाने': 630,
 'शब्दों': 631,
 'हुआ।': 632,
 'करनी': 633,
 '4': 634,
 'अवसर': 635,
 'रात': 636,
 'सीमा': 637,
 'होगा।': 638,
 '000': 639,
 'इतनी': 640,
 'देखते': 641,
 'होंगे': 642,
 'अगले': 643,
 '10': 644,
 'देखें': 645,
 'रखते': 646,
 'संबंधित': 647,
 'नए': 648,
 'भविष्य': 649,
 'हिंदुस्तान': 650,
 'ज्ञान': 651,
 'पक्ष': 652,
 'टन': 653,
 'सिंह': 654,
 'डी': 655,
 'भिन्न': 656,
 'गाड़ी': 657,
 'मार्च': 658,
 'सामग्री': 659,
 'मुसलमानों': 660,
 'जन्म': 661,
 'आई': 662,
 'सदस्यों': 663,
 'आधारित': 664,
 'दर': 665,
 'सारी': 666,
 'मिला': 667,
 'शताब्दी': 668,
 'निकट': 669,
 'प्रभावित': 670,
 'जिला': 671,
 'हो।': 672,
 'पे': 673,
 'नगर': 674,
 'विशाल': 675,
 'पद': 676,
 'टी': 677,
 'कवि': 678,
 'फ़ोन': 679,
 'उद्देश्य': 680,
 'अनुभव': 681,
 'विशिष्ट': 682,
 'पाँच': 683,
 'फिल्म': 684,
 'गति': 685,
 'करे': 686,
 'दशक': 687,
 'दोनो': 688,
 'पी': 689,
 'ना': 690,
 'भाषाओं': 691,
 'जल्दी': 692,
 'पुराने': 693,
 'लगाया': 694,
 'समुद्र': 695,
 'संपर्क': 696,
 'बिजली': 697,
 'सऋ': 698,
 'आते': 699,
 'की।': 700,
 'मंदिरों': 701,
 'सौर': 702,
 'जान': 703,
 'रख': 704,
 'कहना': 705,
 'कहानी': 706,
 'बच्चन': 707,
 'लोक': 708,
 'संभव': 709,
 'मान': 710,
 'रखना': 711,
 '6': 712,
 'टॉम': 713,
 'कितनी': 714,
 'आजादी': 715,
 'अतिरिक्त': 716,
 'य': 717,
 'प्रसिद्ध': 718,
 'मैदान': 719,
 'एन': 720,
 'औद्योगिक': 721,
 'मुसलमान': 722,
 'पाया': 723,
 'विस्तार': 724,
 'पूर्ण': 725,
 'बंगाल': 726,
 'तेजी': 727,
 'हिंदू': 728,
 'प्रचार': 729,
 'रहती': 730,
 'हमे': 731,
 'स्थापना': 732,
 'ईश्वर': 733,
 'प्राकृतिक': 734,
 'राजधानी': 735,
 'तरफ': 736,
 'अनु': 737,
 'नामक': 738,
 'जिन्हें': 739,
 'नेपाल': 740,
 'हजार': 741,
 'जापान': 742,
 'मिलती': 743,
 'पुरस्कार': 744,
 'आमतौर': 745,
 'अंतर्गत': 746,
 'ई': 747,
 'विधेयक': 748,
 'सार्वजनिक': 749,
 'लगती': 750,
 'जाकर': 751,
 'देखने': 752,
 'नया': 753,
 'चरण': 754,
 'सीधे': 755,
 'बढ़': 756,
 'भूमि': 757,
 'गलत': 758,
 'विचारों': 759,
 'सूची': 760,
 'कला': 761,
 'जाएगा': 762,
 'निर्भर': 763,
 'प्रारंभ': 764,
 'प्रशासन': 765,
 'विडियो': 766,
 'वैज्ञानिक': 767,
 'शैली': 768,
 'दिये': 769,
 'सा': 770,
 'थोड़ा': 771,
 '20': 772,
 'सत्र': 773,
 'हमारा': 774,
 'भावना': 775,
 'लगी': 776,
 'नेता': 777,
 'आपका': 778,
 'माँ': 779,
 'प्रकाशित': 780,
 'क': 781,
 'आयु': 782,
 'तुम्हारी': 783,
 'सिद्धांत': 784,
 'लगों': 785,
 'आए': 786,
 'आरंभ': 787,
 'जांच': 788,
 'प्रदूषण': 789,
 'सवाल': 790,
 'धन': 791,
 'मौसम': 792,
 'कितने': 793,
 'प्राचीन': 794,
 'प्रधानमंत्री': 795,
 'प्रकाश': 796,
 'अरब': 797,
 'न्यायाधीश': 798,
 'हवा': 799,
 'सेना': 800,
 'वर्णन': 801,
 'जनवरी': 802,
 'जिनमें': 803,
 'मुख़्य': 804,
 'समझ': 805,
 'निर्धारित': 806,
 'दर्शन': 807,
 'महसूस': 808,
 'आर': 809,
 'जाति': 810,
 'जिले': 811,
 'विरोध': 812,
 'पारित': 813,
 'सक्रिय': 814,
 'फ़िर': 815,
 'संघर्ष': 816,
 'पश्चिम': 817,
 'लागू': 818,
 'मंत्री': 819,
 'जरूरत': 820,
 'मिले': 821,
 'प्रकट': 822,
 'पुत्र': 823,
 'पश्चिमी': 824,
 'असली': 825,
 'सम्मान': 826,
 'a': 827,
 'राजस्थान': 828,
 'हिस्सा': 829,
 'संदेश': 830,
 'व्यापक': 831,
 'पड़ा': 832,
 'कश्मीर': 833,
 'गए।': 834,
 'पांच': 835,
 'संदर्भ': 836,
 'पालन': 837,
 'लिखी': 838,
 'अधिकारी': 839,
 'सेवाओं': 840,
 'मुस्लिम': 841,
 'कल्पना': 842,
 'दी।': 843,
 'रोक': 844,
 'राष्ट्र': 845,
 '15': 846,
 'कथा': 847,
 'तुलना': 848,
 'अक्सर': 849,
 'बातचीत': 850,
 'चुकी': 851,
 'तेल': 852,
 'महान': 853,
 'सच': 854,
 'जानता': 855,
 'हँसी': 856,
 'जितना': 857,
 'स्थानों': 858,
 'कह': 859,
 'अंतर्राष्ट्रीय': 860,
 'विधान': 861,
 '7': 862,
 'बुद्ध': 863,
 'नेहरू': 864,
 'यद्यपि': 865,
 'जीव': 866,
 'कार्यक्रम': 867,
 'शुरुआत': 868,
 'यू': 869,
 'शासन': 870,
 'वेद': 871,
 'छोटा': 872,
 'रेलवे': 873,
 'सात': 874,
 'सर्वाधिक': 875,
 'जरूरी': 876,
 'कठिन': 877,
 'दिशा': 878,
 'मैच': 879,
 'इनका': 880,
 'जिनका': 881,
 'भगवान': 882,
 'विवाह': 883,
 'दीवार': 884,
 'चीनी': 885,
 'आनंद': 886,
 'मूल्य': 887,
 'विमान': 888,
 'यूरोप': 889,
 'मुश्किल': 890,
 'लगते': 891,
 'लिया।': 892,
 'निकल': 893,
 'भाषण': 894,
 'अवस्था': 895,
 'भोजन': 896,
 'खिलाड़ी': 897,
 'द्वीप': 898,
 'माल': 899,
 'बावजूद': 900,
 'अध्ययन': 901,
 'हिंदी': 902,
 'अतिरिक़्त': 903,
 'खड़े': 904,
 'बातें': 905,
 'ली': 906,
 'पड़ता': 907,
 'रवीन्द्रनाथ': 908,
 'खाने': 909,
 'घोषणा': 910,
 'गर्मी': 911,
 'खोज': 912,
 'कीट': 913,
 'इनकी': 914,
 'एकता': 915,
 'रोग': 916,
 'शिखर': 917,
 'देवी': 918,
 'युग': 919,
 'वाजपेयी': 920,
 'खत्म': 921,
 'कोर्ट': 922,
 'विश्वविद्यालय': 923,
 'आशा': 924,
 'सहायक': 925,
 'विदेश': 926,
 'पुराण': 927,
 'शिकायत': 928,
 'लाल': 929,
 '14': 930,
 'वैसे': 931,
 'उद्योगों': 932,
 'तर्क': 933,
 'सच्चाई': 934,
 'इंग्लैंड': 935,
 'तुमने': 936,
 'ट्यूब': 937,
 'माता': 938,
 'चारों': 939,
 'साधारण': 940,
 'भारी': 941,
 'खुश': 942,
 'आठ': 943,
 'रहना': 944,
 'थोड़ी': 945,
 'गरीब': 946,
 'अधिकारियों': 947,
 'स्वतंत्र': 948,
 'खिलाफ': 949,
 'साबित': 950,
 'नष्ट': 951,
 'एशिया': 952,
 'अमेरिकी': 953,
 'साफ': 954,
 'नियम': 955,
 'तय': 956,
 'व्यक्तिगत': 957,
 'अपराध': 958,
 'सहयोग': 959,
 'मीडिया': 960,
 'आउट': 961,
 'विष्णु': 962,
 'कृष्ण': 963,
 'दंड': 964,
 'अर्थात': 965,
 'चलते': 966,
 'चित्र': 967,
 'इतने': 968,
 'आदेश': 969,
 'वातावरण': 970,
 'मौजूद': 971,
 'उपर': 972,
 'क्रिया': 973,
 'गंभीर': 974,
 'विभाग': 975,
 'तापमान': 976,
 'असर': 977,
 'पूर्वी': 978,
 'दक्षिणी': 979,
 'आसान': 980,
 'उपबंध': 981,
 'जिन': 982,
 'सोच': 983,
 'उत्तरी': 984,
 'उ': 985,
 'तकनीकी': 986,
 'चर्चा': 987,
 'संसदीय': 988,
 'बीमारी': 989,
 'लेना': 990,
 'पुरानी': 991,
 'संकेत': 992,
 'गैर': 993,
 'संसार': 994,
 'चीज़': 995,
 'कानून': 996,
 'समुदाय': 997,
 'कार्यपालिका': 998,
 'योगदान': 999,
 'पश्चात': 1000,
 ...}

In [31]:
len(tokenizer2.word_index)

21879

In [32]:
sequences1 = tokenizer1.texts_to_sequences(x_train)
sequences1

[[11, 8235, 5590, 10, 729, 27, 10, 2648, 20, 5591, 3025],
 [164, 9],
 [16, 7, 302, 4, 506, 562, 455],
 [9,
  10,
  563,
  2,
  379,
  829,
  792,
  5,
  1,
  4337,
  344,
  5,
  1,
  58,
  2,
  2649,
  8236,
  34,
  2,
  1,
  173,
  1353,
  2,
  1,
  2336],
 [3, 33, 139, 1585, 1898, 4, 8237, 73, 2, 1, 133, 2090],
 [1,
  1586,
  2,
  1,
  8238,
  1472,
  5,
  3587,
  94,
  2337,
  26,
  3026,
  161,
  321,
  5,
  4338,
  1724,
  4,
  5592,
  161,
  321,
  3,
  5,
  2650,
  488,
  4,
  4339,
  161,
  321],
 [16, 41, 4, 689, 6, 2338],
 [157, 142, 4, 350, 6, 202, 877, 51, 34, 489, 2, 360, 1725],
 [3027, 11, 1354, 2091, 13, 75, 4, 345, 1354, 2092],
 [142, 4, 1, 5593],
 [89, 17, 647, 70, 26, 3588, 61, 174, 793],
 [5, 284, 1, 5594, 2, 163, 1587, 408, 4, 225, 648, 169, 1185, 140, 117],
 [8239,
  8240,
  54,
  1355,
  2339,
  346,
  47,
  8241,
  8242,
  2093,
  3,
  4340,
  8243,
  758,
  393],
 [280],
 [71, 82, 25, 4, 2651, 68, 541, 276, 419],
 [118, 1, 8244, 170, 878, 16, 1588, 1, 2340, 1267, 3, 1, 440, 3589, 5, 490],
 [43, 30, 123, 74, 935, 43, 30, 123, 74, 430, 6, 8245, 4341, 85],
 [149, 5595, 3, 394, 5595, 2094, 13, 115, 3028],
 [8, 1, 303, 380, 6, 251, 36, 55, 18, 6, 5596, 7, 4, 1268, 9],
 [219,
  4,
  1,
  5597,
  3590,
  3591,
  32,
  35,
  351,
  4342,
  179,
  2652,
  27,
  1356,
  6,
  5598,
  623,
  2,
  3029,
  161,
  321,
  105,
  8,
  2,
  1899],
 [936, 7, 37, 209, 28, 184],
 [519, 81, 381, 9, 8246, 49, 14, 25, 4, 830, 64, 831],
 [322,
  22,
  5599,
  5,
  5600,
  16,
  10,
  1900,
  1901,
  20,
  1,
  174,
  93,
  48,
  4343,
  70,
  11,
  520,
  185,
  3,
  95,
  690,
  158,
  4,
  670],
 [17, 25, 67, 210, 18, 76],
 [1, 3030, 7, 5601, 3, 8247, 8248, 5, 2341],
 [30, 92, 361, 21, 3031, 3, 8249],
 [57,
  1,
  246,
  2,
  38,
  87,
  5,
  6,
  266,
  2,
  12,
  489,
  7,
  624,
  3,
  17,
  257,
  142,
  4,
  5602,
  4,
  1,
  148,
  15,
  91,
  1186,
  50,
  45,
  395,
  3032,
  7],
 [671, 649, 4344, 2, 1, 86],
 [5603, 4, 1, 564],
 [119, 1473, 3592],
 [304,
  6,
  937,
  7,
  175,
  9,
  672,
  1104,
  29,
  1,
  625,
  148,
  180,
  25,
  1,
  141,
  4,
  2095,
  45,
  162,
  985],
 [30, 13, 1589, 6, 1187],
 [9,
  1269,
  120,
  5604,
  8,
  25,
  6,
  3593,
  673,
  2,
  396,
  24,
  8250,
  5605,
  1188,
  9,
  7,
  102,
  8251],
 [18, 6, 202, 62, 3033, 14, 89, 25, 2653],
 [4, 1726, 1, 1189, 3, 4, 647, 1, 1902],
 [8252,
  53,
  8253,
  2342,
  507,
  7,
  6,
  8254,
  2343,
  2096,
  3,
  8255,
  759,
  48,
  8256,
  18,
  51,
  938,
  2097,
  12,
  1105],
 [396],
 [109,
  16,
  542,
  794,
  1357,
  8257,
  5606,
  22,
  2654,
  5,
  5607,
  2344,
  565,
  4,
  1106,
  8258,
  53,
  1037,
  8259,
  986,
  15,
  760,
  3,
  23,
  4345,
  15,
  5608,
  52,
  5,
  674],
 [9, 7, 624, 11, 76, 4, 103, 72, 109, 397],
 [1, 761, 31, 601, 6, 153, 491],
 [12, 7, 98, 45, 1727],
 [1, 2655, 3034, 82, 103, 8260, 2656, 24, 5609, 15, 1474],
 [542, 15, 1270, 650, 939, 28, 292],
 [16, 89, 1038, 15, 4, 1, 3594, 3, 1475, 76, 4, 5610, 6, 159, 11, 70],
 [17, 258, 5, 6, 305, 171],
 [2098,
  32,
  13,
  120,
  28,
  8261,
  8262,
  8263,
  8264,
  8265,
  3,
  8266,
  1,
  173,
  77,
  4,
  1,
  203,
  2,
  8267,
  409,
  8268],
 [16, 41, 579, 4, 103, 136, 26, 8269],
 [16, 7, 1590, 51, 1, 352],
 [44, 8270, 7, 34, 2, 1, 255, 879, 214],
 [119, 1728, 1903, 507, 51, 3035, 492, 795],
 [8271, 53, 1358, 4, 8272, 45, 8273, 2, 1, 760, 267, 10, 121, 8274],
 [1, 2657, 2, 6, 129, 48, 31, 987, 5611, 5612],
 [29, 100, 8, 3595],
 [3596,
  256,
  33,
  3036,
  8275,
  12,
  1904,
  8276,
  33,
  176,
  136,
  5,
  1,
  469,
  2,
  12,
  5613],
 [8277, 3597],
 [154, 1190, 1191, 1476],
 [1039,
  3,
  54,
  3037,
  107,
  13,
  47,
  1591,
  20,
  1,
  2345,
  2346,
  5,
  2347,
  1592,
  2,
  940,
  8278,
  36,
  730,
  8279,
  20,
  8280,
  1,
  5614,
  8281,
  5,
  1039],
 [17, 139, 4, 731, 1040, 276, 117],
 [1, 303, 2099, 8282, 5615, 8283, 8284, 8285, 8286, 3, 4346, 2658, 2, 1, 1359],
 [3, 34, 125, 17, 130, 124, 50, 521],
 [12, 7, 4347, 2, 1593, 8287, 8288, 1905],
 [33, 3038, 4, 4348, 941, 1, 329],
 [17, 281, 49, 3039, 1, 1728, 2, 1, 172, 8289, 57],
 [44, 17, 139, 4, 456, 14],
 [30,
  91,
  226,
  155,
  1,
  117,
  2,
  1,
  8290,
  3,
  95,
  8291,
  26,
  9,
  1,
  8292,
  2,
  508,
  3,
  1,
  732,
  2,
  268,
  66,
  8293,
  733,
  8294,
  65],
 [16, 1107, 84, 942],
 [3, 44, 61, 580, 259, 28, 1, 762, 4349],
 [17, 2348, 85, 38, 172, 763, 2, 1271, 543, 1, 1360],
 [277, 8295],
 [43, 14, 1594, 72, 64, 5616, 880, 9, 36, 269, 14, 8, 64, 1272, 7, 4350],
 [30, 238, 73, 2, 1729, 28, 173],
 [69, 5617, 3598, 8296, 8297, 3598, 8298, 306, 1, 5618, 5, 8299],
 [78, 195, 46, 17, 691, 1361, 72],
 [5,
  1,
  62,
  4351,
  493,
  134,
  211,
  3599,
  24,
  1,
  93,
  3,
  1,
  3040,
  297,
  9,
  10,
  6,
  420,
  2,
  1362,
  64,
  127,
  134,
  6,
  1192,
  2,
  764,
  1477,
  1,
  734,
  362,
  59,
  3,
  4352,
  28,
  6,
  3032,
  27,
  10,
  1108,
  4,
  37,
  1,
  1363],
 [4, 21, 302, 4, 55, 255, 353],
 [1, 522, 8300, 421, 8301, 4, 8302, 3, 8303, 8304],
 [16,
  10,
  102,
  4,
  1,
  3600,
  5,
  441,
  5,
  832,
  5619,
  3,
  566,
  2659,
  16,
  1109,
  4,
  40,
  4,
  602,
  330],
 [159, 2, 3041],
 [50, 7, 214, 307, 21, 5620],
 [331, 1595, 8, 14, 156, 1, 1730, 239],
 [1110, 11, 107, 1, 522, 8305, 57],
 [16, 1731, 308, 4353, 6, 410, 4, 143, 119, 1, 5621, 5622],
 [14, 332, 6, 881, 130, 14],
 [44, 12, 651, 7, 75, 72, 20, 1, 247, 1906],
 [52, 8306, 8307, 196],
 [50,
  360,
  14,
  36,
  1475,
  4,
  25,
  4,
  136,
  14,
  1273,
  985,
  51,
  64,
  603,
  431,
  8308,
  126,
  19,
  1730,
  4354,
  109,
  1,
  1193,
  7,
  544,
  66,
  8309,
  4354,
  65],
 [1194],
 [33, 42, 248, 1268, 1, 1907],
 [16,
  4355,
  8,
  16,
  89,
  21,
  302,
  4,
  55,
  56,
  2100,
  108,
  109,
  1,
  432,
  1041,
  72,
  18,
  70,
  3,
  1732,
  6,
  1596,
  15,
  27,
  16,
  123,
  1364,
  69,
  22,
  2101],
 [652, 99, 117],
 [3, 12, 7, 61, 3601, 4356],
 [20, 8310, 3, 1478, 15, 1, 54, 285],
 [146, 37, 52, 333, 1111, 8311, 1, 8312, 3602, 13, 47, 509, 4, 422, 72],
 [104,
  8313,
  2102,
  170,
  8314,
  3,
  494,
  8315,
  132,
  8316,
  5,
  882,
  57,
  10,
  227,
  8317,
  46,
  5623,
  5624,
  1,
  1365,
  11,
  45,
  470,
  626,
  2,
  796,
  735],
 [46,
  1,
  398,
  1195,
  4,
  1,
  93,
  2,
  675,
  91,
  471,
  4,
  627,
  22,
  883,
  51,
  1,
  8318,
  433,
  1112,
  41,
  175,
  6,
  2103,
  1196,
  2,
  1,
  246,
  3,
  2349,
  22,
  1197],
 [442, 4357, 334],
 [2350, 8, 21, 5625],
 [43, 14, 25, 6, 3603, 5626, 14, 25, 6, 209, 4, 25, 1, 267, 8319, 73],
 [9,
  10,
  1479,
  95,
  8,
  1,
  469,
  89,
  21,
  1113,
  74,
  43,
  1,
  3604,
  35,
  3042,
  8320,
  4],
 [8321, 31, 60, 122, 6, 3605, 11, 150],
 [9, 31, 60, 3606, 15, 3, 240, 233, 1, 125, 109, 692],
 [14, 36, 119, 6, 270, 2, 3043, 5, 1, 2104],
 [628, 1274, 604, 50, 2351, 10, 693],
 [879, 765, 8, 2660, 33, 1908, 9, 5, 8322],
 [52, 13, 80, 305, 3044],
 [17, 215, 1, 8323, 18, 61, 8324],
 [14,
  82,
  21,
  302,
  4,
  103,
  2352,
  210,
  43,
  14,
  13,
  3607,
  64,
  184,
  3,
  14,
  82,
  47,
  103,
  136,
  18,
  56,
  54,
  1909,
  3045],
 [30, 137, 298],
 [5627, 230, 7, 80, 131, 4358, 5, 5628, 1, 2353, 567, 2, 2354, 455],
 [46, 17, 653, 61, 323, 3608, 6, 3609, 1191],
 [16, 2105, 8325],
 [1, 5629, 1, 353],
 [2106, 8326, 22, 172, 4359, 1, 286, 125, 3610],
 [43, 14, 335, 28, 8327],
 [3, 17, 94, 41, 186, 8328],
 [11, 1, 4360, 2, 1, 457, 11, 1, 4360, 2, 1, 442],
 [523, 76, 627, 14, 6, 420],
 [12,
  204,
  10,
  91,
  581,
  5,
  3046,
  29,
  45,
  797,
  5,
  524,
  36,
  21,
  5630,
  20,
  1,
  284,
  8,
  9,
  10,
  8329,
  3,
  581,
  260,
  5,
  1480,
  12,
  10,
  214,
  20,
  22,
  3611,
  3612,
  8330,
  2355],
 [12, 988, 1733],
 [3047],
 [98, 150, 25, 14, 3613],
 [71,
  10,
  49,
  56,
  654,
  8331,
  15,
  27,
  1734,
  322,
  1734,
  2,
  443,
  3,
  8332,
  41,
  60,
  4361,
  3,
  309,
  67,
  5631,
  1734,
  41,
  4362,
  24,
  8333,
  50,
  41,
  60,
  299,
  8334],
 [884, 1910],
 [169,
  399,
  655,
  46,
  32,
  7,
  694,
  2356,
  5,
  4363,
  20,
  1,
  272,
  3614,
  261,
  120,
  252,
  9,
  7,
  399,
  655,
  1,
  568,
  1198,
  2,
  1,
  151,
  31,
  164,
  67,
  3048,
  15,
  12,
  655],
 [73, 2, 9, 3615, 8335, 3, 8336, 7, 370],
 [1,
  273,
  5632,
  361,
  4,
  3616,
  11,
  1,
  8337,
  2,
  40,
  53,
  8338,
  209,
  4,
  545,
  3,
  569,
  1,
  1199,
  2,
  6,
  989,
  1275,
  15,
  394,
  3617,
  1481,
  122,
  1,
  2107,
  1597,
  2,
  1735,
  88],
 [3, 30, 335, 28, 12, 8339],
 [5,
  1,
  885,
  943,
  26,
  40,
  520,
  54,
  2357,
  656,
  2,
  1,
  86,
  25,
  6,
  3049,
  431,
  8340,
  1482,
  5,
  510,
  4364,
  329,
  5,
  4365,
  798,
  546,
  3,
  943,
  26,
  52,
  5,
  1,
  8341,
  4366,
  8342,
  8343,
  2661,
  495,
  1,
  324,
  2,
  1,
  5633,
  1483,
  31,
  60,
  4367,
  27,
  7,
  19,
  2108],
 [50, 8344, 3618, 5, 8, 1484, 7, 1, 1114, 2, 676],
 [6,
  336,
  582,
  36,
  21,
  886,
  20,
  6,
  444,
  20,
  386,
  62,
  5634,
  81,
  1,
  5634,
  2,
  1,
  54,
  444,
  104,
  43,
  9,
  180,
  23,
  103,
  1,
  54,
  444,
  37,
  8345],
 [627,
  1,
  766,
  1366,
  1276,
  28,
  64,
  345,
  525,
  4368,
  43,
  30,
  434,
  6,
  1367,
  3050,
  24,
  54,
  766,
  1366,
  1115,
  11,
  196,
  122,
  308],
 [5635],
 [9, 10, 38, 1368, 2, 1, 5636, 601, 5, 39, 8346, 3, 8347],
 [1,
  695,
  31,
  4,
  21,
  3051,
  5,
  1598,
  4,
  1,
  8348,
  3,
  3619,
  1116,
  2,
  6,
  526,
  53,
  696,
  2,
  4369,
  109,
  4370,
  1,
  4369],
 [89, 387, 17, 205, 8349, 5, 64, 3620],
 [9, 7, 1479, 8, 1369, 5637, 88, 44, 1, 2109, 293, 31, 221, 3621, 88],
 [16, 7, 4371, 8, 16, 42, 880, 1, 3052],
 [48, 55, 14, 181, 2110, 1, 2090],
 [17, 25, 6, 242, 629],
 [1,
  792,
  563,
  472,
  1117,
  7,
  3622,
  3623,
  15,
  458,
  4,
  8350,
  1,
  5638,
  239,
  2,
  8351,
  887],
 [19,
  1,
  888,
  2,
  1370,
  228,
  158,
  322,
  670,
  5,
  1,
  185,
  109,
  1,
  8352,
  44,
  9,
  889,
  4,
  76,
  180,
  12,
  888,
  2,
  6,
  8353,
  8354,
  143,
  94,
  4,
  110,
  5,
  1,
  2662,
  2,
  84,
  8355,
  2,
  4372],
 [27, 3053, 8, 677, 2, 32, 115, 38, 8356, 888, 2, 8357],
 [1736, 8358, 3054, 524],
 [388, 630, 890, 26, 40],
 [547, 147, 2111, 72, 20, 693],
 [51, 12, 58, 1, 459, 678, 41, 221, 4373],
 [1,
  5639,
  19,
  2663,
  4374,
  20,
  8359,
  3,
  19,
  1479,
  5,
  22,
  3055,
  5,
  1,
  337,
  7,
  2,
  3624,
  8360,
  18,
  2112,
  3,
  7,
  229,
  8361,
  231],
 [35, 14, 2113],
 [9, 2114, 255, 85, 3625, 346, 346],
 [5640, 2664, 3056],
 [879, 434, 73, 2, 890, 11, 1, 8362],
 [3, 1, 86, 31, 248, 60, 1, 133, 233],
 [5, 527, 445, 1042, 1371, 7, 175, 797, 105, 3057, 3, 108],
 [17, 238, 32, 90, 17, 631, 4],
 [8363,
  13,
  47,
  411,
  11,
  767,
  27,
  7,
  6,
  1911,
  127,
  2,
  2665,
  5,
  767,
  3,
  2666,
  944],
 [32, 71, 7],
 [3, 140, 3058, 8, 3626, 85, 8, 42, 21, 1043, 62, 8364],
 [1,
  5641,
  5642,
  18,
  1,
  300,
  23,
  4,
  166,
  5,
  127,
  4,
  22,
  8365,
  29,
  1,
  300,
  8366],
 [4375, 4376, 3627],
 [3628],
 [1,
  1277,
  1044,
  45,
  3629,
  990,
  15,
  2358,
  991,
  2667,
  46,
  1,
  282,
  5643,
  11,
  1,
  3630,
  1045,
  679,
  1599,
  8367,
  2359,
  6,
  150,
  3629,
  891,
  5644,
  446,
  77,
  447],
 [71, 7, 8368, 15, 768, 4377],
 [1278, 1118, 258, 116],
 [3, 17, 191, 412, 56, 3059, 3, 56, 1200],
 [109, 12, 3631, 10, 23, 2653, 8369, 164, 153, 267],
 [20, 1, 2668, 18, 354, 5, 1737],
 [8370],
 [15,
  1,
  2669,
  30,
  1201,
  1,
  8371,
  51,
  5,
  736,
  3,
  769,
  19,
  6,
  992,
  833,
  97,
  6,
  129,
  8372,
  11,
  1912,
  11,
  6,
  473,
  2360,
  2,
  58,
  27,
  7,
  443,
  4,
  3060,
  4,
  1,
  5645,
  3061,
  16,
  31,
  214],
 [12, 2670, 1913, 51, 1738, 27, 7, 770, 4, 1, 697, 2, 5646],
 [61, 5647, 1739, 31, 1372, 892],
 [54],
 [8373, 8374, 13, 6, 8375, 3062],
 [44, 523, 76, 147, 252, 4, 14, 77, 4378],
 [1485, 36, 103, 4, 83, 993, 67, 382, 98, 305, 6, 1914, 14, 25],
 [16, 893, 49, 6, 1279],
 [363, 5648, 338],
 [5649, 5649, 3063, 13, 47, 75, 66, 799, 65],
 [17,
  257,
  57,
  23,
  6,
  152,
  413,
  8376,
  4,
  25,
  6,
  3593,
  883,
  51,
  1,
  698,
  1600,
  2,
  2361,
  460,
  8377],
 [1, 276, 8378, 7, 4, 699, 8, 351, 179, 5, 371, 260],
 [4379, 4380, 310, 890, 4381],
 [5, 12, 171, 32, 7, 1119, 3, 3064, 86, 47, 27, 7, 370, 20, 1, 177, 2362],
 [12, 58, 16, 7, 800, 5, 8379, 1486],
 [44, 12, 7, 9, 3, 11, 120, 2, 14, 48, 5650, 32],
 [1,
  117,
  1373,
  10,
  222,
  178,
  11,
  192,
  1202,
  364,
  1,
  894,
  632,
  15,
  994,
  1740,
  2,
  8380,
  5651,
  5,
  1280,
  3,
  3065],
 [5652,
  223,
  570,
  736,
  18,
  278,
  605,
  13,
  115,
  226,
  72,
  895,
  5,
  4382,
  18,
  448,
  3632],
 [6, 33, 13, 2363, 2, 1, 262, 1281, 8381, 834, 5, 1, 171],
 [1,
  1601,
  2,
  1,
  410,
  2,
  1,
  277,
  7,
  4,
  1741,
  197,
  3,
  423,
  3,
  945,
  5,
  1,
  277,
  3,
  4,
  5653,
  5,
  1,
  1915,
  2,
  1,
  3633,
  2,
  1,
  93],
 [27, 8382, 1, 1474, 8383, 4383, 1, 91, 5654],
 [144, 92, 21, 175, 109, 3634, 3, 69, 8384],
 [1,
  1916,
  262,
  95,
  4384,
  132,
  61,
  5655,
  7,
  8,
  32,
  7,
  281,
  67,
  1203,
  27,
  36,
  21,
  3635,
  583,
  23,
  18,
  995,
  1,
  2360,
  2,
  58,
  8,
  1,
  1602,
  206,
  5,
  8385,
  1,
  266,
  3,
  27,
  22,
  8386,
  3,
  8387,
  583,
  5656,
  1203,
  57],
 [3636, 3066, 31, 1046, 4, 5657, 5, 1, 548, 2, 198],
 [11,
  4385,
  37,
  1,
  700,
  1374,
  31,
  4,
  21,
  252,
  15,
  1,
  528,
  1,
  1120,
  3637,
  771,
  362,
  1,
  1120,
  1120,
  946,
  36,
  21,
  214,
  20,
  1,
  2115,
  74,
  22,
  541,
  7,
  4,
  1917,
  1,
  414,
  362,
  1,
  1120,
  156,
  2116,
  2364,
  16,
  31,
  1,
  801,
  4,
  1917,
  1,
  414,
  19,
  16,
  7,
  362,
  1,
  1120,
  16,
  36,
  8388,
  73,
  1,
  737],
 [16, 41, 147, 8389, 1, 3638],
 [1, 2365, 238, 72, 4, 694],
 [17, 1204, 64, 177, 4, 70],
 [50, 1, 129, 137, 30, 4386],
 [1,
  525,
  2,
  113,
  10,
  4,
  21,
  6,
  8390,
  293,
  23,
  496,
  4,
  1918,
  29,
  34,
  355,
  2,
  45,
  272,
  35,
  4,
  5658,
  140,
  355,
  117],
 [253, 896, 206, 76, 4, 22, 424],
 [52,
  767,
  13,
  219,
  4,
  39,
  1487,
  835,
  85,
  77,
  1603,
  1,
  8391,
  8392,
  17,
  310,
  1,
  5659,
  2,
  1,
  5660,
  4387,
  90,
  32,
  30,
  4388,
  5660,
  4387,
  26,
  1,
  2671,
  2,
  1,
  5661,
  5662,
  27,
  30,
  836,
  5,
  1,
  546,
  3,
  8393,
  17,
  310,
  1,
  5659,
  2,
  1,
  8394,
  5663,
  26,
  5661,
  3067,
  3,
  128,
  11,
  8395,
  415,
  1,
  8396,
  2,
  1,
  4389],
 [130, 166, 72, 947],
 [3, 651, 3068, 5, 39, 162, 680],
 [2659,
  46,
  5664,
  2,
  3639,
  1604,
  886,
  145,
  311,
  2,
  12,
  113,
  30,
  571,
  52,
  8397,
  897,
  2,
  39,
  8398,
  24,
  3597],
 [16, 306, 6, 5665, 3, 6, 4390],
 [5,
  1,
  2117,
  458,
  1,
  570,
  3,
  1724,
  2,
  8399,
  3,
  282,
  8400,
  35,
  8401,
  4,
  96,
  72,
  26,
  511,
  5666,
  1185,
  837,
  3,
  508,
  351,
  1185,
  837,
  5,
  3069,
  1742,
  4,
  351,
  694,
  1185,
  837,
  3,
  681,
  507,
  1185,
  837,
  1743,
  5,
  1919,
  3640],
 [3, 95, 335, 28, 449],
 [2366,
  356,
  8402,
  48,
  10,
  6,
  572,
  4,
  3641,
  2672,
  219,
  4,
  1,
  3642,
  2,
  1,
  572,
  2366,
  238,
  4,
  584,
  8403,
  6,
  1375],
 [2673, 3070, 5, 39, 167],
 [5, 1, 2367, 259, 2, 767, 1, 216, 898, 2, 449, 738, 7, 2118, 3071],
 [51,
  12,
  58,
  16,
  228,
  5,
  3072,
  772,
  18,
  5667,
  3643,
  48,
  41,
  383,
  191,
  1,
  1920,
  948,
  1,
  8404,
  8405],
 [15, 5668, 650, 30, 372, 73, 11, 2368, 5, 6, 8406],
 [32, 13, 67, 8407, 5, 529, 682],
 [20,
  1,
  241,
  2,
  12,
  243,
  122,
  8408,
  8409,
  3,
  8410,
  1605,
  8411,
  1376,
  287,
  3644,
  5,
  113,
  294,
  41,
  5669,
  5670],
 [24, 141, 4, 5671],
 [16, 47, 1744, 8, 739, 414, 26, 215, 288, 7, 5672, 2656],
 [98, 4, 2119],
 [132,
  6,
  242,
  62,
  78,
  2,
  2674,
  57,
  8412,
  38,
  701,
  132,
  3,
  37,
  8,
  42,
  21,
  215,
  2,
  52,
  4391,
  13,
  1,
  1596,
  3,
  6,
  4392,
  2,
  2120,
  57],
 [20, 12, 33, 36, 1282, 3645, 740, 1121, 3, 2369],
 [16, 7, 68, 763],
 [1, 899, 8413, 802, 1745, 72],
 [1201, 585, 14, 13, 412, 1, 303, 996],
 [677,
  33,
  3646,
  19,
  33,
  244,
  55,
  1,
  432,
  113,
  2121,
  2,
  1377,
  5673,
  3,
  4393,
  8414],
 [3, 17, 1746, 52, 312, 5674, 15, 6, 3073, 497],
 [104, 5, 1, 4394, 2, 40],
 [1047, 1283, 1357, 8415, 19, 1747, 2, 5675],
 [1, 2675, 1921, 672, 8416],
 [1, 136, 1, 199, 14, 603, 11, 633],
 [12,
  41,
  222,
  60,
  1588,
  20,
  1,
  586,
  4395,
  2676,
  5,
  441,
  3,
  20,
  120,
  48,
  838,
  322,
  40,
  19,
  6,
  8417,
  2,
  2677,
  1606,
  11,
  167,
  549,
  2122,
  2,
  87,
  4396,
  228,
  4,
  21,
  8418,
  207,
  1,
  1601,
  15,
  59,
  115,
  839,
  81,
  120,
  15,
  1,
  2122,
  2,
  2677,
  1606],
 [40, 4397, 1, 8419, 1748, 1048, 474, 773, 5, 3074],
 [34,
  125,
  146,
  1,
  997,
  10,
  4398,
  5,
  6,
  1749,
  8420,
  137,
  5676,
  57,
  527,
  64,
  253,
  5677,
  5678,
  3,
  657,
  5679,
  13,
  1590,
  4,
  119,
  14],
 [8421,
  2,
  79,
  8422,
  22,
  162,
  3,
  120,
  2,
  22,
  629,
  5,
  40,
  670,
  3,
  490,
  16,
  10,
  23,
  2123,
  4,
  6,
  8423,
  165,
  5,
  1,
  2124],
 [17, 573, 5, 1, 741, 17, 8424, 255, 73],
 [2125, 134, 52, 77],
 [8425, 277],
 [43,
  32,
  21,
  83,
  5680,
  48,
  205,
  69,
  606,
  1,
  1922,
  28,
  1,
  355,
  170,
  475,
  634,
  2370,
  4,
  1106,
  1,
  2371,
  24,
  83,
  2,
  59,
  27,
  25,
  383,
  60,
  550,
  8,
  7,
  192,
  382,
  29,
  19,
  3647,
  37,
  120,
  48,
  256,
  8426,
  50,
  31,
  60,
  214,
  309,
  4399,
  4,
  106,
  38,
  1284,
  160,
  5,
  1,
  476,
  11,
  1607,
  8427,
  56,
  2371,
  5681,
  4,
  373,
  2126,
  92,
  21,
  1049,
  17,
  55,
  947,
  8,
  1,
  8428,
  17,
  25,
  94,
  60,
  302,
  4,
  166,
  59,
  42,
  3648,
  59,
  2,
  1,
  8429,
  2,
  4400,
  5,
  38,
  3075,
  5,
  1,
  1285,
  2,
  27,
  33,
  13,
  774,
  19,
  2372,
  949,
  19,
  384,
  607,
  5682,
  24,
  2678,
  57],
 [1,
  2373,
  1378,
  10,
  8,
  2,
  1,
  113,
  2,
  8430,
  20,
  1,
  8431,
  3,
  8432,
  1205,
  3649,
  5,
  2374,
  3,
  3650],
 [12,
  177,
  10,
  175,
  20,
  1,
  174,
  5683,
  233,
  30,
  41,
  6,
  1750,
  288,
  5,
  2679,
  12,
  99,
  289,
  5,
  1,
  87,
  608,
  3,
  35,
  1608,
  4,
  1,
  477,
  4,
  21,
  2375,
  20,
  12,
  289],
 [6,
  5684,
  82,
  21,
  2680,
  134,
  1,
  1369,
  3076,
  2376,
  3,
  1,
  565,
  803,
  24,
  1,
  4401,
  2681],
 [8433, 8434, 2666, 313, 3, 2682, 8435, 8436, 313, 7, 263, 19, 8437],
 [16, 2683, 4, 25, 75, 2377, 11, 22, 224],
 [282, 5685, 39, 13, 77, 702, 169, 168, 282, 5685],
 [120,
  339,
  48,
  101,
  23,
  1488,
  4,
  12,
  289,
  29,
  228,
  32,
  384,
  5,
  39,
  701,
  570,
  24,
  19,
  2127,
  47,
  1609,
  3651,
  18,
  12,
  289,
  3,
  104,
  1923,
  1,
  2684,
  2,
  1206,
  19,
  9,
  10,
  774,
  1610,
  5,
  1,
  5686,
  4,
  2378,
  8438,
  1924,
  4,
  143,
  4,
  8439,
  66,
  829,
  144,
  65],
 [2379, 8440, 28, 37, 20, 50, 10, 1286],
 [29,
  46,
  16,
  10,
  3077,
  4,
  1,
  2128,
  16,
  653,
  6,
  2129,
  129,
  48,
  10,
  1379,
  302,
  4,
  1207],
 [6,
  1925,
  36,
  456,
  1,
  528,
  212,
  412,
  73,
  43,
  16,
  998,
  38,
  4402,
  95,
  16,
  36,
  456,
  19,
  2380,
  8441,
  16,
  42,
  21,
  2381,
  20,
  1,
  276,
  1925,
  16,
  7,
  3652,
  19,
  2380,
  4403,
  24,
  2380,
  804,
  2380,
  1925,
  7,
  6,
  23,
  73,
  3,
  16,
  36,
  143,
  260,
  195],
 [3, 30, 13, 587, 105, 3078],
 [50,
  33,
  374,
  8442,
  50,
  33,
  244,
  2685,
  4,
  8443,
  5,
  84,
  948,
  8444,
  9,
  7,
  8,
  2382,
  110,
  73,
  2,
  1,
  3653,
  2,
  3654,
  3,
  8445,
  8446,
  3,
  8447,
  85,
  38,
  8448,
  2,
  1,
  5687,
  3079,
  2,
  84,
  8449],
 [6, 99, 673, 3655],
 [9, 7, 102, 300, 2, 3080, 8450],
 [29, 46, 703, 49, 1206, 228, 72, 30, 89, 8451],
 [7, 9, 142, 4, 21, 61, 658],
 [1, 8452, 456, 9, 188, 1268, 22, 158],
 [2383, 101, 23, 114, 83, 5688, 24, 416, 11, 2686],

In [33]:
from keras.utils import pad_sequences
sequences1 = pad_sequences(sequences1,padding='post')
sequences1

array([[  11, 8235, 5590, ...,    0,    0,    0],
       [ 164,    9,    0, ...,    0,    0,    0],
       [  16,    7,  302, ...,    0,    0,    0],
       ...,
       [  79, 2272,  252, ...,    0,    0,    0],
       [  25,   60,  214, ...,    0,    0,    0],
       [5410, 3817, 5470, ...,    0,    0,    0]], dtype=int32)

In [34]:
len(sequences1[0])

227

In [35]:
sequences2 = tokenizer2.texts_to_sequences(y_train)
sequences2

[[1, 3927, 3, 144, 3928, 550, 26, 24, 9658, 6347, 23, 3929, 156, 88, 2],
 [1, 6348, 14, 16, 2],
 [1, 29, 431, 4840, 2282, 855, 18, 2],
 [1,
  17,
  6349,
  668,
  4,
  2505,
  3930,
  3,
  528,
  4841,
  4,
  8,
  13,
  9659,
  3,
  62,
  4,
  1527,
  2283,
  1191,
  8,
  514,
  34,
  26,
  2],
 [1, 7, 51, 270, 11, 6, 1066, 212, 15, 408, 13, 2506, 8, 181, 2059, 2],
 [1,
  4842,
  4,
  6350,
  1887,
  10,
  203,
  310,
  4,
  3931,
  235,
  8,
  2507,
  6351,
  235,
  21,
  34,
  7,
  1627,
  310,
  4,
  17,
  6352,
  235,
  75,
  2],
 [1, 92, 9660, 313, 832, 2],
 [1, 1067, 3306, 10, 13, 68, 2],
 [1, 6353, 1008, 3, 19, 1748, 584, 499, 6353, 3932, 9, 769, 137, 11, 2],
 [1, 2060, 137, 62, 2],
 [1, 27, 46, 33, 71, 409, 923, 4, 334, 8, 9661, 2],
 [1, 2508, 6354, 1425, 9, 4843, 12, 3933, 13, 242, 2509, 10, 1009, 432, 5, 2],
 [1,
  107,
  1426,
  4,
  3934,
  3935,
  3936,
  3937,
  7,
  3938,
  1628,
  262,
  23,
  15,
  3939,
  3940,
  321,
  10,
  801,
  30,
  18,
  2],
 [1, 856, 2],
 [1, 71, 314, 58, 1068, 643, 515, 9662, 3307, 2],
 [1,
  6355,
  4844,
  4,
  6356,
  6357,
  311,
  3,
  47,
  4,
  95,
  1192,
  2510,
  12,
  565,
  37,
  1427,
  2511,
  3,
  201,
  4,
  76,
  749,
  2284,
  10,
  500,
  60,
  3941,
  3,
  283,
  4,
  959,
  236,
  2],
 [1, 127, 128, 710, 1888, 7, 3942, 6, 9663, 9, 2],
 [1, 3943, 37, 3944, 688, 68, 10, 417, 6358, 30, 52, 18, 2],
 [1, 14, 6359, 3, 38, 6360, 118, 263, 84, 71, 9664, 22, 25, 93, 18, 2],
 [1,
  4845,
  6,
  9665,
  3,
  182,
  433,
  644,
  9666,
  1629,
  3945,
  44,
  6361,
  2512,
  6,
  2513,
  4,
  3946,
  235,
  6,
  516,
  9667,
  9668,
  2],
 [1, 186, 4, 212, 35, 397, 18, 2],
 [1, 264, 71, 9669, 288, 90, 138, 17, 28, 3, 19, 149, 2],
 [1,
  2061,
  9670,
  1010,
  106,
  23,
  1131,
  3308,
  22,
  59,
  7,
  123,
  130,
  1011,
  4,
  1347,
  375,
  889,
  1749,
  236,
  2],
 [1, 122, 97, 185, 49, 566, 16, 36, 2],
 [1, 2865, 45, 86, 432, 5, 7, 529, 35, 3947, 770, 64, 5, 2],
 [1, 204, 1750, 2285, 99, 7, 1750, 32, 2062, 4, 2514, 99, 2],
 [1,
  205,
  148,
  53,
  367,
  4,
  13,
  114,
  6,
  9671,
  221,
  890,
  5,
  7,
  33,
  1069,
  9672,
  179,
  427,
  1630,
  711,
  6362,
  2],
 [1, 216, 199, 3, 243, 1193, 1194, 584, 2],
 [1, 315, 39, 3309, 2866, 2],
 [1, 1428, 4846, 645, 2],
 [1,
  13,
  120,
  460,
  189,
  59,
  359,
  27,
  29,
  528,
  368,
  52,
  5,
  298,
  1528,
  256,
  9,
  32,
  2867,
  10,
  4847,
  28,
  6,
  482,
  5,
  2],
 [1, 40, 1429, 350, 66, 36, 2],
 [1, 209, 6363, 1751, 3, 610, 3948, 69, 3, 91, 179, 121, 9673, 18, 2],
 [1, 126, 9674, 771, 7, 6364, 64, 27, 124, 2868, 21, 6365, 2],
 [1, 1348, 7, 1349, 9, 2286, 2],
 [1,
  9675,
  3,
  772,
  1889,
  9676,
  2515,
  10,
  9677,
  3949,
  9678,
  5,
  7,
  40,
  20,
  773,
  4,
  1195,
  2869,
  9679,
  73,
  9680,
  9681,
  213,
  115,
  11,
  2],
 [1, 418, 2],
 [1,
  9682,
  23,
  2870,
  611,
  9,
  9683,
  3,
  1196,
  9684,
  9,
  1890,
  833,
  367,
  4,
  1752,
  6,
  3310,
  180,
  7,
  71,
  1197,
  47,
  4,
  70,
  3950,
  6,
  2063,
  3951,
  6,
  2],
 [1, 122, 19, 1430, 461, 8, 81, 6366, 45, 890, 18, 2],
 [1, 6367, 6, 6368, 327, 501, 116, 5, 2],
 [1, 93, 18, 2],
 [1,
  87,
  91,
  2064,
  6,
  4848,
  4,
  1132,
  1349,
  31,
  3952,
  279,
  1275,
  12,
  2871,
  69,
  750,
  5,
  2],
 [1, 2065, 1891, 802, 2516, 9, 3311, 1276, 2],
 [1,
  128,
  6369,
  9,
  1198,
  585,
  7,
  551,
  924,
  646,
  14,
  33,
  67,
  19,
  2287,
  9685,
  22,
  6370,
  2],
 [1, 33, 237, 258, 4, 316, 152, 2],
 [1,
  206,
  111,
  3,
  107,
  552,
  226,
  9686,
  9687,
  9688,
  6371,
  6371,
  9689,
  7,
  9690,
  4,
  11,
  803,
  528,
  89,
  9691,
  3,
  9692,
  9693,
  3,
  669,
  11,
  2],
 [1, 1350, 2517, 8, 246, 9694, 10, 2872, 30, 88, 2],
 [1, 29, 3953, 3, 19, 3312, 18, 2],
 [1, 27, 6372, 133, 1753, 4, 8, 13, 5, 24, 280, 30, 5, 110, 2],
 [1, 230, 265, 12, 4849, 2066, 3, 94, 4, 1428, 1754, 772, 645, 2],
 [1,
  9695,
  6,
  4850,
  9696,
  23,
  833,
  434,
  20,
  386,
  8,
  2873,
  3,
  19,
  165,
  3313,
  4,
  517,
  30,
  2],
 [1, 2518, 1277, 251, 3, 6373, 9697, 23, 6374, 9698, 1755, 30, 2],
 [1, 12, 17, 612, 6375, 5, 2],
 [1,
  51,
  2288,
  8,
  1631,
  142,
  613,
  398,
  6,
  304,
  9,
  2289,
  22,
  3954,
  78,
  183,
  20,
  6376,
  6,
  399,
  4,
  925,
  227,
  99,
  2],
 [1, 6377, 1632, 2],
 [1, 247, 1278, 1199, 6378, 9699, 2],
 [1,
  266,
  10,
  689,
  1012,
  1133,
  1633,
  8,
  3314,
  37,
  160,
  435,
  1892,
  10,
  139,
  670,
  64,
  5,
  1132,
  4851,
  6,
  2067,
  4,
  3314,
  3,
  6379,
  10,
  9700,
  6380,
  104,
  8,
  2874,
  335,
  4,
  3315,
  80,
  5,
  2],
 [1, 65, 643, 140, 926, 751, 1756, 28, 10, 502, 18, 2],
 [1,
  9701,
  9702,
  9703,
  9704,
  7,
  1351,
  10,
  4852,
  671,
  20,
  1757,
  3,
  9705,
  1758,
  626,
  11,
  2],
 [1, 7, 13, 130, 690, 104, 46, 75, 14, 2],
 [1, 17, 9706, 1134, 6381, 3, 3316, 10, 2519, 18, 2],
 [1, 51, 336, 9, 9707, 1352, 22, 4853, 2],
 [1, 65, 2068, 6382, 3, 2875, 15, 518, 891, 3317, 2],
 [1, 4, 138, 4854, 410, 157, 2],
 [1,
  81,
  27,
  40,
  2520,
  284,
  10,
  167,
  585,
  11,
  7,
  614,
  8,
  712,
  10,
  3955,
  7,
  519,
  10,
  376,
  9708,
  1135,
  6383,
  9709,
  228,
  11,
  2],
 [1, 100, 774, 436, 377, 22, 892, 2],
 [1, 27, 960, 9710, 4, 233, 1353, 305, 2],
 [1, 65, 1893, 3, 181, 149, 13, 1431, 1070, 285, 210, 2],
 [1, 9711, 671, 2],
 [1,
  126,
  42,
  149,
  9712,
  97,
  4855,
  11,
  29,
  42,
  9,
  1279,
  48,
  5,
  14,
  567,
  1529,
  530,
  8,
  5,
  2],
 [1, 40, 1759, 2290, 8, 181, 893, 834, 2],
 [1, 4856, 4857, 9713, 3, 55, 9714, 4857, 9715, 9716, 4, 3956, 4858, 2],
 [1, 1013, 55, 61, 33, 1894, 211, 101, 2],
 [1,
  749,
  9717,
  279,
  106,
  7,
  2069,
  8,
  647,
  76,
  1200,
  483,
  4,
  179,
  531,
  26,
  2521,
  3,
  2522,
  4,
  8,
  9718,
  9719,
  54,
  2876,
  9720,
  3318,
  83,
  289,
  6384,
  54,
  6385,
  775,
  9,
  2285,
  7,
  148,
  1630,
  12,
  9721,
  24,
  103,
  2523,
  3,
  19,
  3319,
  54,
  9722,
  21,
  2],
 [1, 532, 47, 8, 187, 28, 3, 19, 2],
 [1, 9723, 360, 10, 419, 5, 9724, 129, 9725, 2],
 [1,
  1280,
  6386,
  4,
  92,
  2524,
  3,
  120,
  4,
  252,
  30,
  34,
  7,
  83,
  55,
  6387,
  25,
  40,
  84,
  28,
  3,
  9726,
  8,
  43,
  1634,
  1071,
  2],
 [1, 4859, 568, 2],
 [1, 24, 21, 553, 5, 1635, 21, 553, 18, 2],
 [1, 1014, 17, 1760, 22, 1761, 14, 42, 427, 4860, 10, 201, 22, 1530, 11, 2],
 [1, 1762, 3, 19, 5, 360, 1762, 2],
 [1, 6388, 2877, 752, 3, 19, 100, 337, 8, 835, 2525, 1531, 156, 2],
 [1, 387, 97, 13, 1532, 5, 5, 70, 2],
 [1, 9727, 17, 338, 1763, 3957, 2070, 57, 627, 36, 2],
 [1, 50, 2526, 6389, 267, 11, 2],
 [1, 1201, 2],
 [1, 836, 2],
 [1, 51, 2291, 153, 16, 9728, 2],
 [1,
  92,
  924,
  56,
  14,
  569,
  3,
  2878,
  8,
  81,
  25,
  35,
  2292,
  84,
  22,
  9729,
  7,
  9730,
  1072,
  9731,
  2879,
  6390,
  3,
  55,
  84,
  22,
  6391,
  2],
 [1, 648, 140, 6, 9732, 2],
 [1, 7, 50, 233, 9733, 5, 2],
 [1, 6392, 7, 3958, 23, 351, 30, 2],
 [1,
  2527,
  50,
  306,
  9734,
  891,
  11,
  78,
  173,
  4,
  1073,
  334,
  143,
  3959,
  15,
  1636,
  69,
  776,
  11,
  2],
 [1,
  218,
  39,
  14,
  9735,
  23,
  61,
  3320,
  9,
  1637,
  1354,
  10,
  2880,
  4861,
  69,
  12,
  9736,
  9737,
  27,
  253,
  777,
  7,
  1202,
  3,
  9738,
  6393,
  9739,
  15,
  6394,
  8,
  339,
  184,
  2],
 [1,
  61,
  1281,
  106,
  3,
  804,
  2071,
  23,
  9740,
  1015,
  12,
  105,
  340,
  1432,
  3,
  19,
  411,
  120,
  584,
  472,
  27,
  1282,
  23,
  3960,
  8,
  2528,
  10,
  1433,
  30,
  7,
  58,
  340,
  8,
  3961,
  1638,
  26,
  2],
 [1, 649, 927, 2],
 [1, 9741, 84, 10, 16, 136, 2],
 [1, 126, 567, 928, 628, 5, 27, 778, 295, 5, 14, 567, 386, 9742, 361, 2],
 [1,
  79,
  62,
  96,
  34,
  26,
  14,
  1354,
  10,
  9743,
  8,
  837,
  28,
  12,
  25,
  399,
  238,
  6,
  1355,
  2],
 [1, 9744, 3321, 8, 1533, 3, 4862, 4, 11, 2],
 [1, 6395, 8, 1016, 1764, 1764, 3, 21, 116, 18, 2],
 [1, 352, 2881, 4, 45, 328, 4863, 570, 9745, 2],
 [1, 713, 9, 174, 6, 85, 805, 16, 3962, 2],
 [1,
  280,
  128,
  369,
  1074,
  166,
  5,
  280,
  1136,
  9746,
  4,
  25,
  159,
  2072,
  22,
  59,
  26,
  2],
 [1, 50, 4864, 45, 237, 36, 2],
 [1, 131, 9747, 9, 32, 6396, 3, 38, 473, 236, 2],
 [1,
  126,
  42,
  554,
  3,
  19,
  753,
  1137,
  2073,
  66,
  5,
  27,
  42,
  9,
  3322,
  566,
  285,
  72,
  5,
  7,
  42,
  9,
  1066,
  10,
  1137,
  9748,
  1356,
  4,
  15,
  322,
  959,
  285,
  48,
  5,
  2],
 [1, 281, 26, 520, 2],
 [1,
  1895,
  691,
  10,
  9749,
  806,
  28,
  4,
  1017,
  329,
  45,
  76,
  925,
  1203,
  101,
  18,
  2],
 [1, 61, 131, 58, 779, 9, 6397, 1199, 4, 1434, 2529, 299, 2],
 [1, 29, 9750, 213, 210, 2],
 [1, 857, 692, 1765, 9751, 2],
 [1, 1896, 3, 160, 130, 1639, 32, 693, 9752, 586, 228, 36, 2],
 [1, 127, 42, 9753, 12, 2882, 2],
 [1, 27, 102, 122, 97, 272, 9754, 196, 2],
 [1, 484, 3, 144, 7, 649, 3, 144, 2],
 [1, 1534, 13, 533, 4865, 152, 2],
 [1,
  17,
  1138,
  9755,
  4,
  411,
  120,
  780,
  101,
  56,
  78,
  450,
  3,
  168,
  4,
  87,
  587,
  10,
  3963,
  206,
  85,
  8,
  694,
  63,
  48,
  5,
  14,
  119,
  3964,
  2883,
  4,
  4866,
  362,
  780,
  6,
  113,
  20,
  84,
  9,
  67,
  25,
  4867,
  9756,
  2074,
  23,
  3965,
  236,
  2],
 [1, 474, 474, 50, 212, 2075, 2],
 [1, 3966, 2],
 [1, 124, 714, 530, 8, 2530, 22, 66, 21, 2],
 [1,
  17,
  53,
  693,
  148,
  9757,
  286,
  26,
  251,
  12,
  9758,
  190,
  7,
  588,
  588,
  9759,
  838,
  101,
  307,
  7,
  55,
  4,
  251,
  12,
  53,
  7,
  23,
  15,
  32,
  190,
  7,
  588,
  588,
  9760,
  9,
  4868,
  62,
  81,
  781,
  1357,
  9,
  70,
  9761,
  21,
  2],
 [1, 3323, 2531, 2],
 [1,
  234,
  230,
  1204,
  1640,
  4869,
  37,
  1766,
  28,
  9762,
  3,
  1018,
  8,
  76,
  311,
  25,
  230,
  1204,
  5,
  20,
  1204,
  10,
  589,
  6,
  433,
  311,
  568,
  8,
  49,
  485,
  273,
  64,
  5,
  2],
 [1, 803, 9763, 7, 9764, 118, 1075, 36, 2],
 [1,
  204,
  2076,
  650,
  6,
  715,
  7,
  6398,
  3,
  3324,
  295,
  6,
  1076,
  3,
  19,
  9765,
  503,
  8,
  590,
  57,
  521,
  173,
  28,
  6,
  4870,
  451,
  5,
  24,
  611,
  268,
  3,
  1139,
  4,
  136,
  2],
 [1, 7, 128, 20, 9766, 9, 9767, 2],
 [1,
  486,
  4,
  43,
  3,
  716,
  199,
  3,
  123,
  107,
  2884,
  858,
  10,
  836,
  15,
  432,
  5,
  90,
  475,
  10,
  9768,
  9769,
  9770,
  6,
  2077,
  336,
  929,
  1283,
  37,
  87,
  716,
  486,
  3,
  2885,
  1284,
  3,
  9771,
  9772,
  1284,
  4,
  2078,
  615,
  10,
  2886,
  15,
  571,
  34,
  5,
  24,
  1535,
  5,
  2],
 [1, 79, 1285, 4871, 23, 24, 299, 128, 807, 6, 1358, 5, 2],
 [1,
  353,
  4,
  437,
  9,
  202,
  534,
  197,
  22,
  15,
  4872,
  63,
  48,
  5,
  476,
  292,
  522,
  9,
  238,
  68,
  8,
  961,
  70,
  30,
  34,
  672,
  2],
 [1,
  42,
  3,
  2887,
  504,
  3,
  839,
  9,
  79,
  3,
  499,
  9773,
  6399,
  4,
  751,
  9774,
  14,
  46,
  29,
  9775,
  140,
  6,
  782,
  3,
  523,
  3,
  293,
  3,
  19,
  1897,
  9776,
  6400,
  781,
  9777,
  31,
  2888,
  2887,
  504,
  3,
  1019,
  1897,
  1767,
  10,
  2079,
  60,
  5,
  2],
 [1, 6401, 2],
 [1, 17, 3967, 108, 10, 1435, 26, 24, 67, 6402, 7, 9778, 4, 6403, 52, 26, 2],
 [1,
  53,
  311,
  10,
  3968,
  377,
  28,
  8,
  193,
  462,
  10,
  1630,
  21,
  178,
  550,
  5,
  14,
  29,
  3968,
  427,
  5,
  7,
  3969,
  8,
  59,
  34,
  5,
  2],
 [1, 46, 33, 146, 783, 2889, 4, 16, 9779, 2],
 [1,
  96,
  52,
  5,
  14,
  1898,
  23,
  1768,
  60,
  82,
  96,
  27,
  2080,
  10,
  341,
  9780,
  10,
  21,
  34,
  2],
 [1, 524, 1286, 5, 14, 29, 1769, 4, 97, 21, 1536, 2],
 [1, 352, 46, 198, 5, 2506, 3970, 6404, 5, 2],
 [1, 122, 97, 35, 1070, 36, 2],
 [1,
  1537,
  627,
  9781,
  226,
  1436,
  628,
  9782,
  9783,
  5,
  208,
  9784,
  962,
  6,
  6405,
  101,
  2532,
  5,
  2],
 [1,
  397,
  2293,
  25,
  90,
  14,
  2294,
  3,
  300,
  12,
  889,
  4,
  6406,
  3,
  81,
  3,
  463,
  4,
  299,
  63,
  48,
  26,
  20,
  68,
  10,
  9785,
  122,
  19,
  13,
  68,
  6,
  6407,
  9786,
  717,
  9787,
  286,
  1205,
  64,
  5,
  24,
  9788,
  6,
  1132,
  9789,
  3,
  150,
  808,
  30,
  63,
  48,
  5,
  2],
 [1, 251, 8, 50, 192, 254, 14, 53, 1437, 1020, 3, 354, 3, 1206, 2],
 [1, 1641, 1642, 10, 1438, 450, 2],
 [1, 216, 43, 3, 1194, 584, 2],
 [1, 33, 58, 85, 50, 859, 22, 6408, 77, 3325, 2],
 [1, 194, 206, 62, 860, 304, 6409, 21, 113, 2],
 [1,
  6410,
  286,
  14,
  9790,
  10,
  9791,
  26,
  7,
  286,
  14,
  226,
  4,
  83,
  4873,
  4,
  96,
  34,
  5,
  2080,
  6,
  9792,
  9793,
  9794,
  6,
  5,
  7,
  438,
  9795,
  591,
  1643,
  5,
  2],
 [1, 46, 352, 2890, 400, 113, 56, 2],
 [1, 195, 2295, 10, 13, 3971, 1644, 5, 2],
 [1, 6411, 9796, 2891, 112, 11, 2],
 [1, 9797, 4, 9798, 1538, 21, 34, 18, 2],
 [1, 7, 219, 342, 342, 3, 586, 2081, 2],
 [1,
  930,
  592,
  963,
  1439,
  1077,
  4,
  651,
  7,
  1645,
  3,
  244,
  12,
  1440,
  9,
  9799,
  166,
  113,
  18,
  2],
 [1, 33, 330, 34, 151, 233, 502, 88, 2],
 [1,
  9800,
  15,
  2533,
  262,
  3,
  19,
  317,
  11,
  24,
  14,
  2533,
  141,
  3326,
  3327,
  12,
  104,
  10,
  13,
  2082,
  9801,
  36,
  2],
 [1, 29, 330, 5, 2],
 [1, 7, 9802, 47, 8, 20, 84, 4, 2534, 73, 162, 1140, 10, 2],
 [1, 363, 9803, 23, 6412, 6, 14, 9804, 135, 3328, 354, 271, 2],
 [1, 86, 9805, 2],
 [1, 2296, 2],
 [1,
  1770,
  1539,
  1141,
  4874,
  9,
  32,
  528,
  754,
  4,
  3972,
  61,
  1899,
  3,
  177,
  9806,
  592,
  1287,
  1540,
  9807,
  23,
  194,
  89,
  515,
  2535,
  528,
  6413,
  894,
  59,
  2],
 [1, 29, 200, 1078, 12, 9808, 2],
 [1, 171, 1900, 388, 4875, 82, 36, 2],
 [1, 7, 65, 9809, 7, 3973, 334, 9810, 2],
 [1,
  195,
  81,
  2083,
  3,
  1541,
  68,
  1359,
  21,
  104,
  8,
  1646,
  9,
  2084,
  3974,
  389,
  196,
  2],
 [1, 3975, 3, 439, 3, 4876, 6, 378, 8, 2],
 [1, 9811, 2],
 [1,
  87,
  1142,
  40,
  1441,
  10,
  4877,
  7,
  2892,
  6,
  1647,
  4,
  9812,
  9813,
  895,
  616,
  11,
  239,
  487,
  13,
  3976,
  62,
  39,
  964,
  1207,
  316,
  5,
  7,
  29,
  62,
  83,
  57,
  245,
  115,
  9814,
  3,
  1648,
  368,
  52,
  5,
  2],
 [1,
  17,
  1357,
  6414,
  3,
  1771,
  8,
  2085,
  440,
  73,
  809,
  452,
  452,
  3,
  94,
  4,
  18,
  2],
 [1, 122, 1542, 3, 1438, 3977, 21, 115, 36, 2],
 [1, 107, 2],
 [1, 6415, 6415, 13, 9815, 810, 5, 2],
 [1, 27, 65, 42, 3, 19, 505, 477, 89, 4878, 4, 11, 2],
 [1,
  49,
  15,
  53,
  1543,
  673,
  63,
  48,
  5,
  476,
  778,
  2297,
  1079,
  15,
  2536,
  355,
  70,
  21,
  2],
 [1, 29, 2298, 4, 1649, 6, 68, 198, 18, 2],
 [1, 453, 6416, 6417, 6418, 6419, 6420, 2],
 [1, 9816, 3978, 9817, 15, 30, 52, 11, 2],
 [1,
  33,
  49,
  290,
  9818,
  16,
  401,
  14,
  2893,
  322,
  784,
  3,
  9819,
  6421,
  3,
  94,
  4,
  49,
  2299,
  340,
  189,
  9820,
  2],
 [1, 1143, 3979, 5, 79, 13, 1021, 9, 2894, 77, 2],
 [1, 1193, 2537, 2538, 584, 2539, 4, 2],
 [1,
  674,
  4,
  43,
  10,
  247,
  2300,
  129,
  2895,
  308,
  15,
  5,
  24,
  3980,
  121,
  8,
  718,
  18,
  2],
 [1, 20, 120, 1131, 6422, 1011, 4, 402, 210, 2],
 [1, 27, 17, 9821, 7, 42, 4, 1635, 24, 109, 330, 16, 44, 67, 19, 2],
 [1,
  931,
  191,
  54,
  2540,
  13,
  7,
  378,
  8,
  15,
  2541,
  9822,
  420,
  6,
  9823,
  4,
  2086,
  7,
  3329,
  4,
  1901,
  9824,
  3,
  9825,
  3,
  19,
  2],
 [1,
  38,
  38,
  25,
  421,
  1288,
  3,
  675,
  369,
  1772,
  2087,
  63,
  66,
  11,
  24,
  4879,
  535,
  6423,
  3,
  959,
  8,
  11,
  2],
 [1, 51, 258, 4, 785, 6, 593, 1442, 1544, 8, 2542, 11, 2],
 [1,
  671,
  243,
  10,
  84,
  811,
  4,
  861,
  37,
  6424,
  9826,
  77,
  7,
  454,
  4880,
  3,
  84,
  9827,
  246,
  77,
  18,
  2],
 [1, 1022, 89, 2064, 73, 4881, 9, 1443, 514, 5, 81, 2891, 441, 6425, 2],
 [1, 435, 896, 8, 81, 7, 1902, 3330, 3, 55, 9828, 178, 99, 2],
 [1,
  2543,
  1444,
  23,
  87,
  55,
  149,
  652,
  257,
  402,
  1545,
  233,
  1080,
  5,
  14,
  3331,
  6,
  49,
  15,
  240,
  6426,
  16,
  166,
  188,
  5,
  251,
  12,
  2896,
  8,
  190,
  30,
  63,
  356,
  594,
  6427,
  23,
  2301,
  6,
  2302,
  28,
  4,
  221,
  1285,
  156,
  7,
  83,
  9829,
  3981,
  23,
  119,
  13,
  1903,
  9830,
  571,
  205,
  2],
 [1, 2088, 4882, 8, 629, 6, 1208, 1650, 101, 5, 2],
 [1,
  3982,
  3,
  652,
  3,
  103,
  4883,
  897,
  719,
  4,
  13,
  38,
  323,
  11,
  390,
  8,
  13,
  1289,
  3983,
  9831,
  9832,
  9833,
  64,
  5,
  24,
  1904,
  506,
  3,
  57,
  9834,
  104,
  73,
  1289,
  3,
  289,
  1546,
  316,
  5,
  1289,
  6428,
  2897,
  13,
  2089,
  25,
  22,
  48,
  5,
  159,
  327,
  86,
  133,
  6429,
  9,
  6430,
  64,
  5,
  24,
  506,
  2544,
  16,
  93,
  5,
  296,
  6,
  506,
  4884,
  3,
  534,
  690,
  170,
  356,
  29,
  177,
  6431,
  3332,
  11,
  168,
  9835,
  4,
  145,
  408,
  9,
  135,
  28,
  6,
  1008,
  80,
  5,
  38,
  25,
  32,
  9836,
  2090,
  9,
  3333,
  28,
  3,
  19,
  2898,
  15,
  3332,
  5,
  4885,
  29,
  755,
  1904,
  3,
  289,
  1546,
  316,
  5,
  1773,
  83,
  97,
  20,
  85,
  6,
  45,
  76,
  1023,
  80,
  5,
  14,
  128,
  506,
  3,
  6432,
  3,
  1144,
  8,
  6433,
  22,
  2545,
  101,
  6434,
  9,
  9837,
  362,
  506,
  9,
  961,
  22,
  356,
  145,
  612,
  13,
  135,
  897,
  5,
  24,
  506,
  9,
  9838,
  6435,
  961,
  22,
  48,
  5,
  2],
 [1, 100, 185, 185, 32, 6436, 9839, 9840, 9841, 3, 186, 2],
 [1, 102, 4886, 1018, 39, 756, 115, 2],
 [1, 131, 83, 38, 1360, 121, 156, 88, 2],
 [1, 478, 23, 46, 96, 26, 40, 9842, 2],
 [1,
  2303,
  1774,
  4887,
  13,
  2546,
  2547,
  136,
  222,
  4888,
  16,
  30,
  63,
  2548,
  363,
  83,
  13,
  1651,
  311,
  162,
  1547,
  167,
  6437,
  21,
  2091,
  2],
 [1, 1542, 153, 153, 65, 6438, 170, 1905, 60, 196, 2],
 [1,
  50,
  898,
  67,
  1145,
  54,
  9843,
  3,
  1648,
  89,
  2549,
  4,
  9844,
  54,
  1081,
  11,
  6439,
  9845,
  965,
  9846,
  10,
  898,
  1548,
  54,
  2550,
  391,
  40,
  9847,
  4889,
  3,
  9848,
  6,
  3334,
  8,
  1906,
  60,
  11,
  24,
  40,
  695,
  4,
  4890,
  228,
  6440,
  7,
  9849,
  965,
  9850,
  54,
  223,
  10,
  6439,
  24,
  4889,
  3,
  4891,
  8,
  9851,
  22,
  9852,
  117,
  5,
  7,
  1549,
  3,
  9853,
  3984,
  4,
  4892,
  54,
  9854,
  80,
  5,
  2],
 [1, 2551, 354, 6441, 2],
 [1, 7, 32, 139, 4, 4893, 6442, 116, 5, 2],
 [1,
  55,
  4,
  61,
  2552,
  810,
  3,
  9855,
  23,
  20,
  163,
  3,
  2553,
  1024,
  12,
  149,
  9856,
  1025,
  156,
  27,
  133,
  1024,
  10,
  6443,
  32,
  32,
  1445,
  279,
  244,
  3,
  6444,
  22,
  236,
  2],
 [1, 40, 13, 6445, 154, 6446, 3, 47, 4, 104, 104, 389, 2],
 [1,
  301,
  3,
  572,
  7,
  9857,
  4894,
  301,
  4,
  6447,
  1446,
  37,
  177,
  1361,
  6,
  369,
  37,
  310,
  10,
  572,
  191,
  6448,
  2554,
  3,
  862,
  6449,
  242,
  653,
  37,
  712,
  644,
  242,
  653,
  8,
  191,
  2899,
  3985,
  4,
  6450,
  4895,
  644,
  1018,
  242,
  653,
  37,
  1082,
  772,
  242,
  653,
  402,
  2],
 [1, 7, 9858, 3, 503, 1907, 110, 2],
 [1,
  67,
  1775,
  3,
  144,
  2555,
  9859,
  9860,
  9,
  170,
  1071,
  7,
  9861,
  1362,
  3,
  144,
  1083,
  1652,
  2],
 [1, 403, 4, 675, 595, 2059, 2],
 [1, 1908, 898, 305, 4, 3335, 2900, 327, 2901, 1447, 5, 2],
 [1,
  194,
  206,
  62,
  40,
  6451,
  3986,
  3,
  669,
  696,
  4,
  786,
  6452,
  9862,
  1193,
  9863,
  3318,
  787,
  22,
  59,
  26,
  2],
 [1, 802, 1653, 9, 40, 9864, 8, 2556, 2902, 82, 2],
 [1, 2304, 3987, 9865, 4, 9866, 16, 36, 2],
 [1,
  20,
  284,
  3,
  464,
  39,
  1550,
  9867,
  9868,
  7,
  6453,
  6454,
  3,
  573,
  574,
  840,
  4,
  488,
  3336,
  194,
  575,
  21,
  184,
  44,
  2],
 [1, 31, 9869, 28, 6, 482, 2],
 [1,
  175,
  1080,
  17,
  15,
  5,
  14,
  4896,
  343,
  6,
  1132,
  576,
  4897,
  6,
  6455,
  5,
  110,
  2],
 [1, 1654, 291, 271, 2],
 [1,
  13,
  839,
  9870,
  11,
  41,
  41,
  35,
  140,
  7,
  3988,
  116,
  27,
  98,
  6456,
  6,
  404,
  3337,
  7,
  1191,
  3,
  2305,
  9871,
  41,
  41,
  2],
 [1, 87, 966, 6457, 1209, 697, 141, 1909, 6, 2903, 6, 63, 161, 18, 2],
 [1, 29, 159, 1070, 18, 2],
 [1, 1655, 9872, 3338, 9873, 4898, 2],
 [1, 190, 1551, 14, 46, 138, 118, 3989, 6458, 285, 74, 5, 31, 16, 2],
 [1,
  87,
  1142,
  280,
  342,

In [36]:
voc1size=len(tokenizer1.word_index)
voc2size=len(tokenizer2.word_index)

In [37]:
from tensorflow import keras
from tensorflow.keras.layers import Input, Embedding, LSTM, Dense

In [38]:
from tensorflow.keras.models import Model

In [39]:
encoder_inputs = Input(shape=(len(sequences1[0]),), name="encoder_inputs")

In [40]:
encoder_embedding = Embedding(
    input_dim=voc1size,
    output_dim=256,
    mask_zero=True
)(encoder_inputs)

In [41]:
# Layer 1
x, state_h1, state_c1 = LSTM(
    200,
    return_sequences=True,
    return_state=True
)(encoder_embedding)

# Layer 2
x, state_h2, state_c2 = LSTM(
    200,
    return_sequences=True,
    return_state=True
)(x)

# Layer 3
x, state_h3, state_c3 = LSTM(
    200,
    return_sequences=True,
    return_state=True
)(x)

# Layer 4
encoder_outputs, state_h4, state_c4 = LSTM(
    200,
    return_sequences=False,
    return_state=True
)(x)

In [42]:
decoder_inputs = Input(shape=(None,), name="decoder_inputs")

In [43]:
decoder_embedding = Embedding(
    input_dim=voc2size,
    output_dim=256,
    mask_zero=True
)(decoder_inputs)

In [44]:
# Layer 1
x, _, _ = LSTM(
    200,
    return_sequences=True,
    return_state=True
)(
    decoder_embedding,
    initial_state=[state_h1, state_c1]
)

# Layer 2
x, _, _ = LSTM(
    200,
    return_sequences=True,
    return_state=True
)(
    x,
    initial_state=[state_h2, state_c2]
)

# Layer 3
x, _, _ = LSTM(
    200,
    return_sequences=True,
    return_state=True
)(
    x,
    initial_state=[state_h3, state_c3]
)

# Layer 4
decoder_outputs, _, _ = LSTM(
    200,
    return_sequences=True,
    return_state=True
)(
    x,
    initial_state=[state_h4, state_c4]
)

In [45]:
decoder_outputs = Dense(
    voc2size,
    activation="softmax"
)(decoder_outputs)

In [46]:
model = Model(
    [encoder_inputs, decoder_inputs],
    decoder_outputs
)

In [47]:
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

In [48]:
y_train

array(['<START> यज्ञ के लिये घोड़ा आवश्यक था जो ईर्ष्यालु इंद्र ने चुरा लिया था। <END>',
       '<START> समझे कि नहीं? <END>',
       '<START> वह दस भाषाएँ बोलना जानता है। <END>', ...,
       '<START> कई राय आतंकवाद के कारणों के विषय में मौजूद हैं.वे से रेंज जनांकिकीय (demographic) को सामाजिक (socioeconomic) राजनीतिक कारणों के लिए.जनांकिकीय कारकों और भीड़ उच्च विकास दर शामिल हो सकते हैं.सामाजिक कारकों गरीबी बेरोजगारी और भूमि कार्यकाल समस्याओं शामिल हो सकते हैं.राजनैतिक कारक शामिल हो सकते हैं दिसेंफ्रंचिसेमेंट (disenfranchisement) जातीय संघर्ष (ethnic conflict) धार्मिक संघर्ष (religious conflict) प्रादेशिक संघर्ष (territorial conflict) संसाधन या भी बदला लेने का उपयोग करने के लिए. <END>',
       '<START> गति को कब्ज़ा करने वाले कैमरों की मदद से किये गए है| <END>',
       '<START> मुंबई में ही एशिया का सबसे पुराना समाचार-पत्र बॉम्बे समाचार भी निकलता है। <END>'],
      dtype='<U1540')

In [49]:
y_train_tar=pd.DataFrame(y_train)

In [50]:
y_train_tar

                                                       0
0      <START> यज्ञ के लिये घोड़ा आवश्यक था जो ईर्ष्य...
1                            <START> समझे कि नहीं? <END>
2             <START> वह दस भाषाएँ बोलना जानता है। <END>
3      <START> यह नवीं शताब्दी में पल्लव राजवंश के अं...
4      <START> और हम चाहते हैं की बाकी सब भी उसी एक ख...
...                                                  ...
11238  <START> परंतु भारत की अत्यधिक जनसंख्या के कारण...
11239  <START> उनके उत्तराधिकारी कलराज मिश्र की धारणा...
11240  <START> कई राय आतंकवाद के कारणों के विषय में म...
11241  <START> गति को कब्ज़ा करने वाले कैमरों की मदद ...
11242  <START> मुंबई में ही एशिया का सबसे पुराना समाच...

[11243 rows x 1 columns]

In [51]:
y_train_tar.iloc[:, 0] = (
    y_train_tar.iloc[:, 0]
    .str.replace("<START>", "", regex=False)
    .str.strip()
)

In [52]:
y_train_tar=np.array(y_train_tar)

In [53]:
y_train_tar=y_train_tar.reshape(-1)

In [54]:
y_train_tar=y_train_tar.astype(str)

In [55]:
y_train_tar

array(['यज्ञ के लिये घोड़ा आवश्यक था जो ईर्ष्यालु इंद्र ने चुरा लिया था। <END>',
       'समझे कि नहीं? <END>', 'वह दस भाषाएँ बोलना जानता है। <END>', ...,
       'कई राय आतंकवाद के कारणों के विषय में मौजूद हैं.वे से रेंज जनांकिकीय (demographic) को सामाजिक (socioeconomic) राजनीतिक कारणों के लिए.जनांकिकीय कारकों और भीड़ उच्च विकास दर शामिल हो सकते हैं.सामाजिक कारकों गरीबी बेरोजगारी और भूमि कार्यकाल समस्याओं शामिल हो सकते हैं.राजनैतिक कारक शामिल हो सकते हैं दिसेंफ्रंचिसेमेंट (disenfranchisement) जातीय संघर्ष (ethnic conflict) धार्मिक संघर्ष (religious conflict) प्रादेशिक संघर्ष (territorial conflict) संसाधन या भी बदला लेने का उपयोग करने के लिए. <END>',
       'गति को कब्ज़ा करने वाले कैमरों की मदद से किये गए है| <END>',
       'मुंबई में ही एशिया का सबसे पुराना समाचार-पत्र बॉम्बे समाचार भी निकलता है। <END>'],
      dtype='<U1532')

In [56]:
tokenizer3=Tokenizer()

In [57]:
tokenizer3.fit_on_texts(y_train_tar)

In [58]:
sequences3 = tokenizer3.texts_to_sequences(y_train_tar)
sequences3

[[3926, 2, 143, 3927, 549, 25, 23, 9657, 6346, 22, 3928, 155, 87, 1],
 [6347, 13, 15, 1],
 [28, 430, 4839, 2281, 854, 17, 1],
 [16,
  6348,
  667,
  3,
  2504,
  3929,
  2,
  527,
  4840,
  3,
  7,
  12,
  9658,
  2,
  61,
  3,
  1526,
  2282,
  1190,
  7,
  513,
  33,
  25,
  1],
 [6, 50, 269, 10, 5, 1065, 211, 14, 407, 12, 2505, 7, 180, 2058, 1],
 [4841,
  3,
  6349,
  1886,
  9,
  202,
  309,
  3,
  3930,
  234,
  7,
  2506,
  6350,
  234,
  20,
  33,
  6,
  1626,
  309,
  3,
  16,
  6351,
  234,
  74,
  1],
 [91, 9659, 312, 831, 1],
 [1066, 3305, 9, 12, 67, 1],
 [6352, 1007, 2, 18, 1747, 583, 498, 6352, 3931, 8, 768, 136, 10, 1],
 [2059, 136, 61, 1],
 [26, 45, 32, 70, 408, 922, 3, 333, 7, 9660, 1],
 [2507, 6353, 1424, 8, 4842, 11, 3932, 12, 241, 2508, 9, 1008, 431, 4, 1],
 [106,
  1425,
  3,
  3933,
  3934,
  3935,
  3936,
  6,
  3937,
  1627,
  261,
  22,
  14,
  3938,
  3939,
  320,
  9,
  800,
  29,
  17,
  1],
 [855, 1],
 [70, 313, 57, 1067, 642, 514, 9661, 3306, 1],
 [6354,
  4843,
  3,
  6355,
  6356,
  310,
  2,
  46,
  3,
  94,
  1191,
  2509,
  11,
  564,
  36,
  1426,
  2510,
  2,
  200,
  3,
  75,
  748,
  2283,
  9,
  499,
  59,
  3940,
  2,
  282,
  3,
  958,
  235,
  1],
 [126, 127, 709, 1887, 6, 3941, 5, 9662, 8, 1],
 [3942, 36, 3943, 687, 67, 9, 416, 6357, 29, 51, 17, 1],
 [13, 6358, 2, 37, 6359, 117, 262, 83, 70, 9663, 21, 24, 92, 17, 1],
 [4844,
  5,
  9664,
  2,
  181,
  432,
  643,
  9665,
  1628,
  3944,
  43,
  6360,
  2511,
  5,
  2512,
  3,
  3945,
  234,
  5,
  515,
  9666,
  9667,
  1],
 [185, 3, 211, 34, 396, 17, 1],
 [263, 70, 9668, 287, 89, 137, 16, 27, 2, 18, 148, 1],
 [2060,
  9669,
  1009,
  105,
  22,
  1130,
  3307,
  21,
  58,
  6,
  122,
  129,
  1010,
  3,
  1346,
  374,
  888,
  1748,
  235,
  1],
 [121, 96, 184, 48, 565, 15, 35, 1],
 [2864, 44, 85, 431, 4, 6, 528, 34, 3946, 769, 63, 4, 1],
 [203, 1749, 2284, 98, 6, 1749, 31, 2061, 3, 2513, 98, 1],
 [204,
  147,
  52,
  366,
  3,
  12,
  113,
  5,
  9670,
  220,
  889,
  4,
  6,
  32,
  1068,
  9671,
  178,
  426,
  1629,
  710,
  6361,
  1],
 [215, 198, 2, 242, 1192, 1193, 583, 1],
 [314, 38, 3308, 2865, 1],
 [1427, 4845, 644, 1],
 [12,
  119,
  459,
  188,
  58,
  358,
  26,
  28,
  527,
  367,
  51,
  4,
  297,
  1527,
  255,
  8,
  31,
  2866,
  9,
  4846,
  27,
  5,
  481,
  4,
  1],
 [39, 1428, 349, 65, 35, 1],
 [208, 6362, 1750, 2, 609, 3947, 68, 2, 90, 178, 120, 9672, 17, 1],
 [125, 9673, 770, 6, 6363, 63, 26, 123, 2867, 20, 6364, 1],
 [1347, 6, 1348, 8, 2285, 1],
 [9674,
  2,
  771,
  1888,
  9675,
  2514,
  9,
  9676,
  3948,
  9677,
  4,
  6,
  39,
  19,
  772,
  3,
  1194,
  2868,
  9678,
  72,
  9679,
  9680,
  212,
  114,
  10,
  1],
 [417, 1],
 [9681,
  22,
  2869,
  610,
  8,
  9682,
  2,
  1195,
  9683,
  8,
  1889,
  832,
  366,
  3,
  1751,
  5,
  3309,
  179,
  6,
  70,
  1196,
  46,
  3,
  69,
  3949,
  5,
  2062,
  3950,
  5,
  1],
 [121, 18, 1429, 460, 7, 80, 6365, 44, 889, 17, 1],
 [6366, 5, 6367, 326, 500, 115, 4, 1],
 [92, 17, 1],
 [86,
  90,
  2063,
  5,
  4847,
  3,
  1131,
  1348,
  30,
  3951,
  278,
  1274,
  11,
  2870,
  68,
  749,
  4,
  1],
 [2064, 1890, 801, 2515, 8, 3310, 1275, 1],
 [127,
  6368,
  8,
  1197,
  584,
  6,
  550,
  923,
  645,
  13,
  32,
  66,
  18,
  2286,
  9684,
  21,
  6369,
  1],
 [32, 236, 257, 3, 315, 151, 1],
 [205,
  110,
  2,
  106,
  551,
  225,
  9685,
  9686,
  9687,
  6370,
  6370,
  9688,
  6,
  9689,
  3,
  10,
  802,
  527,
  88,
  9690,
  2,
  9691,
  9692,
  2,
  668,
  10,
  1],
 [1349, 2516, 7, 245, 9693, 9, 2871, 29, 87, 1],
 [28, 3952, 2, 18, 3311, 17, 1],
 [26, 6371, 132, 1752, 3, 7, 12, 4, 23, 279, 29, 4, 109, 1],
 [229, 264, 11, 4848, 2065, 2, 93, 3, 1427, 1753, 771, 644, 1],
 [9694,
  5,
  4849,
  9695,
  22,
  832,
  433,
  19,
  385,
  7,
  2872,
  2,
  18,
  164,
  3312,
  3,
  516,
  29,
  1],
 [2517, 1276, 250, 2, 6372, 9696, 22, 6373, 9697, 1754, 29, 1],
 [11, 16, 611, 6374, 4, 1],
 [50,
  2287,
  7,
  1630,
  141,
  612,
  397,
  5,
  303,
  8,
  2288,
  21,
  3953,
  77,
  182,
  19,
  6375,
  5,
  398,
  3,
  924,
  226,
  98,
  1],
 [6376, 1631, 1],
 [246, 1277, 1198, 6377, 9698, 1],
 [265,
  9,
  688,
  1011,
  1132,
  1632,
  7,
  3313,
  36,
  159,
  434,
  1891,
  9,
  138,
  669,
  63,
  4,
  1131,
  4850,
  5,
  2066,
  3,
  3313,
  2,
  6378,
  9,
  9699,
  6379,
  103,
  7,
  2873,
  334,
  3,
  3314,
  79,
  4,
  1],
 [64, 642, 139, 925, 750, 1755, 27, 9, 501, 17, 1],
 [9700,
  9701,
  9702,
  9703,
  6,
  1350,
  9,
  4851,
  670,
  19,
  1756,
  2,
  9704,
  1757,
  625,
  10,
  1],
 [6, 12, 129, 689, 103, 45, 74, 13, 1],
 [16, 9705, 1133, 6380, 2, 3315, 9, 2518, 17, 1],
 [50, 335, 8, 9706, 1351, 21, 4852, 1],
 [64, 2067, 6381, 2, 2874, 14, 517, 890, 3316, 1],
 [3, 137, 4853, 409, 156, 1],
 [80,
  26,
  39,
  2519,
  283,
  9,
  166,
  584,
  10,
  6,
  613,
  7,
  711,
  9,
  3954,
  6,
  518,
  9,
  375,
  9707,
  1134,
  6382,
  9708,
  227,
  10,
  1],
 [99, 773, 435, 376, 21, 891, 1],
 [26, 959, 9709, 3, 232, 1352, 304, 1],
 [64, 1892, 2, 180, 148, 12, 1430, 1069, 284, 209, 1],
 [9710, 670, 1],
 [125,
  41,
  148,
  9711,
  96,
  4854,
  10,
  28,
  41,
  8,
  1278,
  47,
  4,
  13,
  566,
  1528,
  529,
  7,
  4,
  1],
 [39, 1758, 2289, 7, 180, 892, 833, 1],
 [4855, 4856, 9712, 2, 54, 9713, 4856, 9714, 9715, 3, 3955, 4857, 1],
 [1012, 54, 60, 32, 1893, 210, 100, 1],
 [748,
  9716,
  278,
  105,
  6,
  2068,
  7,
  646,
  75,
  1199,
  482,
  3,
  178,
  530,
  25,
  2520,
  2,
  2521,
  3,
  7,
  9717,
  9718,
  53,
  2875,
  9719,
  3317,
  82,
  288,
  6383,
  53,
  6384,
  774,
  8,
  2284,
  6,
  147,
  1629,
  11,
  9720,
  23,
  102,
  2522,
  2,
  18,
  3318,
  53,
  9721,
  20,
  1],
 [531, 46, 7, 186, 27, 2, 18, 1],
 [9722, 359, 9, 418, 4, 9723, 128, 9724, 1],
 [1279,
  6385,
  3,
  91,
  2523,
  2,
  119,
  3,
  251,
  29,
  33,
  6,
  82,
  54,
  6386,
  24,
  39,
  83,
  27,
  2,
  9725,
  7,
  42,
  1633,
  1070,
  1],
 [4858, 567, 1],
 [23, 20, 552, 4, 1634, 20, 552, 17, 1],
 [1013, 16, 1759, 21, 1760, 13, 41, 426, 4859, 9, 200, 21, 1529, 10, 1],
 [1761, 2, 18, 4, 359, 1761, 1],
 [6387, 2876, 751, 2, 18, 99, 336, 7, 834, 2524, 1530, 155, 1],
 [386, 96, 12, 1531, 4, 4, 69, 1],
 [9726, 16, 337, 1762, 3956, 2069, 56, 626, 35, 1],
 [49, 2525, 6388, 266, 10, 1],
 [1200, 1],
 [835, 1],
 [50, 2290, 152, 15, 9727, 1],
 [91,
  923,
  55,
  13,
  568,
  2,
  2877,
  7,
  80,
  24,
  34,
  2291,
  83,
  21,
  9728,
  6,
  9729,
  1071,
  9730,
  2878,
  6389,
  2,
  54,
  83,
  21,
  6390,
  1],
 [647, 139, 5, 9731, 1],
 [6, 49, 232, 9732, 4, 1],
 [6391, 6, 3957, 22, 350, 29, 1],
 [2526,
  49,
  305,
  9733,
  890,
  10,
  77,
  172,
  3,
  1072,
  333,
  142,
  3958,
  14,
  1635,
  68,
  775,
  10,
  1],
 [217,
  38,
  13,
  9734,
  22,
  60,
  3319,
  8,
  1636,
  1353,
  9,
  2879,
  4860,
  68,
  11,
  9735,
  9736,
  26,
  252,
  776,
  6,
  1201,
  2,
  9737,
  6392,
  9738,
  14,
  6393,
  7,
  338,
  183,
  1],
 [60,
  1280,
  105,
  2,
  803,
  2070,
  22,
  9739,
  1014,
  11,
  104,
  339,
  1431,
  2,
  18,
  410,
  119,
  583,
  471,
  26,
  1281,
  22,
  3959,
  7,
  2527,
  9,
  1432,
  29,
  6,
  57,
  339,
  7,
  3960,
  1637,
  25,
  1],
 [648, 926, 1],
 [9740, 83, 9, 15, 135, 1],
 [125, 566, 927, 627, 4, 26, 777, 294, 4, 13, 566, 385, 9741, 360, 1],
 [78,
  61,
  95,
  33,
  25,
  13,
  1353,
  9,
  9742,
  7,
  836,
  27,
  11,
  24,
  398,
  237,
  5,
  1354,
  1],
 [9743, 3320, 7, 1532, 2, 4861, 3, 10, 1],
 [6394, 7, 1015, 1763, 1763, 2, 20, 115, 17, 1],
 [351, 2880, 3, 44, 327, 4862, 569, 9744, 1],
 [712, 8, 173, 5, 84, 804, 15, 3961, 1],
 [279,
  127,
  368,
  1073,
  165,
  4,
  279,
  1135,
  9745,
  3,
  24,
  158,
  2071,
  21,
  58,
  25,
  1],
 [49, 4863, 44, 236, 35, 1],
 [130, 9746, 8, 31, 6395, 2, 37, 472, 235, 1],
 [125,
  41,
  553,
  2,
  18,
  752,
  1136,
  2072,
  65,
  4,
  26,
  41,
  8,
  3321,
  565,
  284,
  71,
  4,
  6,
  41,
  8,
  1065,
  9,
  1136,
  9747,
  1355,
  3,
  14,
  321,
  958,
  284,
  47,
  4,
  1],
 [280, 25, 519, 1],
 [1894, 690, 9, 9748, 805, 27, 3, 1016, 328, 44, 75, 924, 1202, 100, 17, 1],
 [60, 130, 57, 778, 8, 6396, 1198, 3, 1433, 2528, 298, 1],
 [28, 9749, 212, 209, 1],
 [856, 691, 1764, 9750, 1],
 [1895, 2, 159, 129, 1638, 31, 692, 9751, 585, 227, 35, 1],
 [126, 41, 9752, 11, 2881, 1],
 [26, 101, 121, 96, 271, 9753, 195, 1],
 [483, 2, 143, 6, 648, 2, 143, 1],
 [1533, 12, 532, 4864, 151, 1],
 [16,
  1137,
  9754,
  3,
  410,
  119,
  779,
  100,
  55,
  77,
  449,
  2,
  167,
  3,
  86,
  586,
  9,
  3962,
  205,
  84,
  7,
  693,
  62,
  47,
  4,
  13,
  118,
  3963,
  2882,
  3,
  4865,
  361,
  779,
  5,
  112,
  19,
  83,
  8,
  66,
  24,
  4866,
  9755,
  2073,
  22,
  3964,
  235,
  1],
 [473, 473, 49, 211, 2074, 1],
 [3965, 1],
 [123, 713, 529, 7, 2529, 21, 65, 20, 1],
 [16,
  52,
  692,
  147,
  9756,
  285,
  25,
  250,
  11,
  9757,
  189,
  6,
  587,
  587,
  9758,
  837,
  100,
  306,
  6,
  54,
  3,
  250,
  11,
  52,
  6,
  22,
  14,
  31,
  189,
  6,
  587,
  587,
  9759,
  8,
  4867,
  61,
  80,
  780,
  1356,
  8,
  69,
  9760,
  20,
  1],
 [3322, 2530, 1],
 [233,
  229,
  1203,
  1639,
  4868,
  36,
  1765,
  27,
  9761,
  2,
  1017,
  7,
  75,
  310,
  24,
  229,
  1203,
  4,
  19,
  1203,
  9,
  588,
  5,
  432,
  310,
  567,
  7,
  48,
  484,
  272,
  63,
  4,
  1],
 [802, 9762, 6, 9763, 117, 1074, 35, 1],
 [203,
  2075,
  649,
  5,
  714,
  6,
  6397,
  2,
  3323,
  294,
  5,
  1075,
  2,
  18,
  9764,
  502,
  7,
  589,
  56,
  520,
  172,
  27,
  5,
  4869,
  450,
  4,
  23,
  610,
  267,
  2,
  1138,
  3,
  135,
  1],
 [6, 127, 19, 9765, 8, 9766, 1],
 [485,
  3,
  42,
  2,
  715,
  198,
  2,
  122,
  106,
  2883,
  857,
  9,
  835,
  14,
  431,
  4,
  89,
  474,
  9,
  9767,
  9768,
  9769,
  5,
  2076,
  335,
  928,
  1282,
  36,
  86,
  715,
  485,
  2,
  2884,
  1283,
  2,
  9770,
  9771,
  1283,
  3,
  2077,
  614,
  9,
  2885,
  14,
  570,
  33,
  4,
  23,
  1534,
  4,
  1],
 [78, 1284, 4870, 22, 23, 298, 127, 806, 5, 1357, 4, 1],
 [352,
  3,
  436,
  8,
  201,
  533,
  196,
  21,
  14,
  4871,
  62,
  47,
  4,
  475,
  291,
  521,
  8,
  237,
  67,
  7,
  960,
  69,
  29,
  33,
  671,
  1],
 [41,
  2,
  2886,
  503,
  2,
  838,
  8,
  78,
  2,
  498,
  9772,
  6398,
  3,
  750,
  9773,
  13,
  45,
  28,
  9774,
  139,
  5,
  781,
  2,
  522,
  2,
  292,
  2,
  18,
  1896,
  9775,
  6399,
  780,
  9776,
  30,
  2887,
  2886,
  503,
  2,
  1018,
  1896,
  1766,
  9,
  2078,
  59,
  4,
  1],
 [6400, 1],
 [16, 3966, 107, 9, 1434, 25, 23, 66, 6401, 6, 9777, 3, 6402, 51, 25, 1],
 [52,
  310,
  9,
  3967,
  376,
  27,
  7,
  192,
  461,
  9,
  1629,
  20,
  177,
  549,
  4,
  13,
  28,
  3967,
  426,
  4,
  6,
  3968,
  7,
  58,
  33,
  4,
  1],
 [45, 32, 145, 782, 2888, 3, 15, 9778, 1],
 [95,
  51,
  4,
  13,
  1897,
  22,
  1767,
  59,
  81,
  95,
  26,
  2079,
  9,
  340,
  9779,
  9,
  20,
  33,
  1],
 [523, 1285, 4, 13, 28, 1768, 3, 96, 20, 1535, 1],
 [351, 45, 197, 4, 2505, 3969, 6403, 4, 1],
 [121, 96, 34, 1069, 35, 1],
 [1536,
  626,
  9780,
  225,
  1435,
  627,
  9781,
  9782,
  4,
  207,
  9783,
  961,
  5,
  6404,
  100,
  2531,
  4,
  1],
 [396,
  2292,
  24,
  89,
  13,
  2293,
  2,
  299,
  11,
  888,
  3,
  6405,
  2,
  80,
  2,
  462,
  3,
  298,
  62,
  47,
  25,
  19,
  67,
  9,
  9784,
  121,
  18,
  12,
  67,
  5,
  6406,
  9785,
  716,
  9786,
  285,
  1204,
  63,
  4,
  23,
  9787,
  5,
  1131,
  9788,
  2,
  149,
  807,
  29,
  62,
  47,
  4,
  1],
 [250, 7, 49, 191, 253, 13, 52, 1436, 1019, 2, 353, 2, 1205, 1],
 [1640, 1641, 9, 1437, 449, 1],
 [215, 42, 2, 1193, 583, 1],
 [32, 57, 84, 49, 858, 21, 6407, 76, 3324, 1],
 [193, 205, 61, 859, 303, 6408, 20, 112, 1],
 [6409,
  285,
  13,
  9789,
  9,
  9790,
  25,
  6,
  285,
  13,
  225,
  3,
  82,
  4872,
  3,
  95,
  33,
  4,
  2079,
  5,
  9791,
  9792,
  9793,
  5,
  4,
  6,
  437,
  9794,
  590,
  1642,
  4,
  1],
 [45, 351, 2889, 399, 112, 55, 1],
 [194, 2294, 9, 12, 3970, 1643, 4, 1],
 [6410, 9795, 2890, 111, 10, 1],
 [9796, 3, 9797, 1537, 20, 33, 17, 1],
 [6, 218, 341, 341, 2, 585, 2080, 1],
 [929,
  591,
  962,
  1438,
  1076,
  3,
  650,
  6,
  1644,
  2,
  243,
  11,
  1439,
  8,
  9798,
  165,
  112,
  17,
  1],
 [32, 329, 33, 150, 232, 501, 87, 1],
 [9799,
  14,
  2532,
  261,
  2,
  18,
  316,
  10,
  23,
  13,
  2532,
  140,
  3325,
  3326,
  11,
  103,
  9,
  12,
  2081,
  9800,
  35,
  1],
 [28, 329, 4, 1],
 [6, 9801, 46, 7, 19, 83, 3, 2533, 72, 161, 1139, 9, 1],
 [362, 9802, 22, 6411, 5, 13, 9803, 134, 3327, 353, 270, 1],
 [85, 9804, 1],
 [2295, 1],
 [1769,
  1538,
  1140,
  4873,
  8,
  31,
  527,
  753,
  3,
  3971,
  60,
  1898,
  2,
  176,
  9805,
  591,
  1286,
  1539,
  9806,
  22,
  193,
  88,
  514,
  2534,
  527,
  6412,
  893,
  58,
  1],
 [28, 199, 1077, 11, 9807, 1],
 [170, 1899, 387, 4874, 81, 35, 1],
 [6, 64, 9808, 6, 3972, 333, 9809, 1],
 [194,
  80,
  2082,
  2,
  1540,
  67,
  1358,
  20,
  103,
  7,
  1645,
  8,
  2083,
  3973,
  388,
  195,
  1],
 [3974, 2, 438, 2, 4875, 5, 377, 7, 1],
 [9810, 1],
 [86,
  1141,
  39,
  1440,
  9,
  4876,
  6,
  2891,
  5,
  1646,
  3,
  9811,
  9812,
  894,
  615,
  10,
  238,
  486,
  12,
  3975,
  61,
  38,
  963,
  1206,
  315,
  4,
  6,
  28,
  61,
  82,
  56,
  244,
  114,
  9813,
  2,
  1647,
  367,
  51,
  4,
  1],
 [16, 1356, 6413, 2, 1770, 7, 2084, 439, 72, 808, 451, 451, 2, 93, 3, 17, 1],
 [121, 1541, 2, 1437, 3976, 20, 114, 35, 1],
 [106, 1],
 [6414, 6414, 12, 9814, 809, 4, 1],
 [26, 64, 41, 2, 18, 504, 476, 88, 4877, 3, 10, 1],
 [48,
  14,
  52,
  1542,
  672,
  62,
  47,
  4,
  475,
  777,
  2296,
  1078,
  14,
  2535,
  354,
  69,
  20,
  1],
 [28, 2297, 3, 1648, 5, 67, 197, 17, 1],
 [452, 6415, 6416, 6417, 6418, 6419, 1],
 [9815, 3977, 9816, 14, 29, 51, 10, 1],
 [32,
  48,
  289,
  9817,
  15,
  400,
  13,
  2892,
  321,
  783,
  2,
  9818,
  6420,
  2,
  93,
  3,
  48,
  2298,
  339,
  188,
  9819,
  1],
 [1142, 3978, 4, 78, 12, 1020, 8, 2893, 76, 1],
 [1192, 2536, 2537, 583, 2538, 3, 1],
 [673,
  3,
  42,
  9,
  246,
  2299,
  128,
  2894,
  307,
  14,
  4,
  23,
  3979,
  120,
  7,
  717,
  17,
  1],
 [19, 119, 1130, 6421, 1010, 3, 401, 209, 1],
 [26, 16, 9820, 6, 41, 3, 1634, 23, 108, 329, 15, 43, 66, 18, 1],
 [930,
  190,
  53,
  2539,
  12,
  6,
  377,
  7,
  14,
  2540,
  9821,
  419,
  5,
  9822,
  3,
  2085,
  6,
  3328,
  3,
  1900,
  9823,
  2,
  9824,
  2,
  18,
  1],
 [37,
  37,
  24,
  420,
  1287,
  2,
  674,
  368,
  1771,
  2086,
  62,
  65,
  10,
  23,
  4878,
  534,
  6422,
  2,
  958,
  7,
  10,
  1],
 [50, 257, 3, 784, 5, 592, 1441, 1543, 7, 2541, 10, 1],
 [670,
  242,
  9,
  83,
  810,
  3,
  860,
  36,
  6423,
  9825,
  76,
  6,
  453,
  4879,
  2,
  83,
  9826,
  245,
  76,
  17,
  1],
 [1021, 88, 2063, 72, 4880, 8, 1442, 513, 4, 80, 2890, 440, 6424, 1],
 [434, 895, 7, 80, 6, 1901, 3329, 2, 54, 9827, 177, 98, 1],
 [2542,
  1443,
  22,
  86,
  54,
  148,
  651,
  256,
  401,
  1544,
  232,
  1079,
  4,
  13,
  3330,
  5,
  48,
  14,
  239,
  6425,
  15,
  165,
  187,
  4,
  250,
  11,
  2895,
  7,
  189,
  29,
  62,
  355,
  593,
  6426,
  22,
  2300,
  5,
  2301,
  27,
  3,
  220,
  1284,
  155,
  6,
  82,
  9828,
  3980,
  22,
  118,
  12,
  1902,
  9829,
  570,
  204,
  1],
 [2087, 4881, 7, 628, 5, 1207, 1649, 100, 4, 1],
 [3981,
  2,
  651,
  2,
  102,
  4882,
  896,
  718,
  3,
  12,
  37,
  322,
  10,
  389,
  7,
  12,
  1288,
  3982,
  9830,
  9831,
  9832,
  63,
  4,
  23,
  1903,
  505,
  2,
  56,
  9833,
  103,
  72,
  1288,
  2,
  288,
  1545,
  315,
  4,
  1288,
  6427,
  2896,
  12,
  2088,
  24,
  21,
  47,
  4,
  158,
  326,
  85,
  132,
  6428,
  8,
  6429,
  63,
  4,
  23,
  505,
  2543,
  15,
  92,
  4,
  295,
  5,
  505,
  4883,
  2,
  533,
  689,
  169,
  355,
  28,
  176,
  6430,
  3331,
  10,
  167,
  9834,
  3,
  144,
  407,
  8,
  134,
  27,
  5,
  1007,
  79,
  4,
  37,
  24,
  31,
  9835,
  2089,
  8,
  3332,
  27,
  2,
  18,
  2897,
  14,
  3331,
  4,
  4884,
  28,
  754,
  1903,
  2,
  288,
  1545,
  315,
  4,
  1772,
  82,
  96,
  19,
  84,
  5,
  44,
  75,
  1022,
  79,
  4,
  13,
  127,
  505,
  2,
  6431,
  2,
  1143,
  7,
  6432,
  21,
  2544,
  100,
  6433,
  8,
  9836,
  361,
  505,
  8,
  960,
  21,
  355,
  144,
  611,
  12,
  134,
  896,
  4,
  23,
  505,
  8,
  9837,
  6434,
  960,
  21,
  47,
  4,
  1],
 [99, 184, 184, 31, 6435, 9838, 9839, 9840, 2, 185, 1],
 [101, 4885, 1017, 38, 755, 114, 1],
 [130, 82, 37, 1359, 120, 155, 87, 1],
 [477, 22, 45, 95, 25, 39, 9841, 1],
 [2302,
  1773,
  4886,
  12,
  2545,
  2546,
  135,
  221,
  4887,
  15,
  29,
  62,
  2547,
  362,
  82,
  12,
  1650,
  310,
  161,
  1546,
  166,
  6436,
  20,
  2090,
  1],
 [1541, 152, 152, 64, 6437, 169, 1904, 59, 195, 1],
 [49,
  897,
  66,
  1144,
  53,
  9842,
  2,
  1647,
  88,
  2548,
  3,
  9843,
  53,
  1080,
  10,
  6438,
  9844,
  964,
  9845,
  9,
  897,
  1547,
  53,
  2549,
  390,
  39,
  9846,
  4888,
  2,
  9847,
  5,
  3333,
  7,
  1905,
  59,
  10,
  23,
  39,
  694,
  3,
  4889,
  227,
  6439,
  6,
  9848,
  964,
  9849,
  53,
  222,
  9,
  6438,
  23,
  4888,
  2,
  4890,
  7,
  9850,
  21,
  9851,
  116,
  4,
  6,
  1548,
  2,
  9852,
  3983,
  3,
  4891,
  53,
  9853,
  79,
  4,
  1],
 [2550, 353, 6440, 1],
 [6, 31, 138, 3, 4892, 6441, 115, 4, 1],
 [54,
  3,
  60,
  2551,
  809,
  2,
  9854,
  22,
  19,
  162,
  2,
  2552,
  1023,
  11,
  148,
  9855,
  1024,
  155,
  26,
  132,
  1023,
  9,
  6442,
  31,
  31,
  1444,
  278,
  243,
  2,
  6443,
  21,
  235,
  1],
 [39, 12, 6444, 153, 6445, 2, 46, 3, 103, 103, 388, 1],
 [300,
  2,
  571,
  6,
  9856,
  4893,
  300,
  3,
  6446,
  1445,
  36,
  176,
  1360,
  5,
  368,
  36,
  309,
  9,
  571,
  190,
  6447,
  2553,
  2,
  861,
  6448,
  241,
  652,
  36,
  711,
  643,
  241,
  652,
  7,
  190,
  2898,
  3984,
  3,
  6449,
  4894,
  643,
  1017,
  241,
  652,
  36,
  1081,
  771,
  241,
  652,
  401,
  1],
 [6, 9857, 2, 502, 1906, 109, 1],
 [66,
  1774,
  2,
  143,
  2554,
  9858,
  9859,
  8,
  169,
  1070,
  6,
  9860,
  1361,
  2,
  143,
  1082,
  1651,
  1],
 [402, 3, 674, 594, 2058, 1],
 [1907, 897, 304, 3, 3334, 2899, 326, 2900, 1446, 4, 1],
 [193,
  205,
  61,
  39,
  6450,
  3985,
  2,
  668,
  695,
  3,
  785,
  6451,
  9861,
  1192,
  9862,
  3317,
  786,
  21,
  58,
  25,
  1],
 [801, 1652, 8, 39, 9863, 7, 2555, 2901, 81, 1],
 [2303, 3986, 9864, 3, 9865, 15, 35, 1],
 [19,
  283,
  2,
  463,
  38,
  1549,
  9866,
  9867,
  6,
  6452,
  6453,
  2,
  572,
  573,
  839,
  3,
  487,
  3335,
  193,
  574,
  20,
  183,
  43,
  1],
 [30, 9868, 27, 5, 481, 1],
 [174, 1079, 16, 14, 4, 13, 4895, 342, 5, 1131, 575, 4896, 5, 6454, 4, 109, 1],
 [1653, 290, 270, 1],
 [12,
  838,
  9869,
  10,
  40,
  40,
  34,
  139,
  6,
  3987,
  115,
  26,
  97,
  6455,
  5,
  403,
  3336,
  6,
  1190,
  2,
  2304,
  9870,
  40,
  40,
  1],
 [86, 965, 6456, 1208, 696, 140, 1908, 5, 2902, 5, 62, 160, 17, 1],
 [28, 158, 1069, 17, 1],
 [1654, 9871, 3337, 9872, 4897, 1],
 [189, 1550, 13, 45, 137, 117, 3988, 6457, 284, 73, 4, 30, 15, 1],
 [86,
  1141,
  279,
  341,
  5,
  67,
  21,
  9873,
  6,
  4898,
  787,
  2,
  9874,
  1289,
  89,
  502,
  4899,
  1],
 [6, 1909, 247, 378, 11, 24, 426, 97, 2903, 9, 3989, 111, 1290, 1],
 [217, 38, 9875, 42, 5, 9876, 3990, 3, 1],
 [9877, 267, 719, 9878, 6458, 461, 2, 675, 11, 1],
 [26, 28, 2904, 1436, 46, 7, 6459, 20, 51, 4, 1],
 [41, 3991, 2091, 5, 1551, 21, 65, 4, 78, 5, 223, 2, 18, 1],
 [6460,
  53,
  4900,
  2,
  720,
  697,
  53,
  9879,
  4901,
  22,
  6,
  42,
  8,
  408,
  931,
  2,
  18,
  6461,
  53,
  6462,
  898,
  2,
  9880,
  1083,
  9881,
  69,
  178,
  811,
  29,
  25,
  113,
  1144,
  53,
  2556,
  2,
  1291,
  11,
  3335,
  5,
  595,
  6463,
  187,
  1547,
  53,
  2549,
  6461,
  53,
  6462,
  898,
  2,
  1291,
  5,
  616,
  1144,
  53,
  6464,
  898,
  11,
  75,
  9882,
  53,
  780,
  693,
  33,
  1],
 [576,
  6465,
  9883,
  9884,
  1775,
  6466,
  1200,
  3992,
  1200,
  576,
  9885,
  478,
  6465,
  9886,
  1200,
  9887,
  9888,

In [63]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

max_decoder_len = max(len(seq) for seq in sequences2)

sequences2 = pad_sequences(
    sequences2,
    maxlen=max_decoder_len,
    padding='post'
)

sequences3 = pad_sequences(
    sequences3,
    maxlen=max_decoder_len,
    padding='post'
)

In [64]:
print(type(sequences2), sequences2.shape)
print(type(sequences3), sequences3.shape)

<class 'numpy.ndarray'> (11243, 315)
<class 'numpy.ndarray'> (11243, 315)

In [ ]:
model.fit(
    [sequences1, sequences2],
    sequences3,
    batch_size=64,
    epochs=10,
    validation_split=0.2
)

Epoch 1/10
 73/141 ━━━━━━━━━━━━━━━━━━━━ 45s 672ms/step - accuracy: 0.0540 - loss: 8.6543